/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as AdminStepRequestsRouteImport } from './routes/admin/step-requests'
import { Route as AdminPricingRouteImport } from './routes/admin/pricing'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as LocaleQuoteRouteImport } from './routes/$locale/quote'
import { Route as LocaleOrdersRouteImport } from './routes/$locale/orders'
import { Route as LocaleLoginRouteImport } from './routes/$locale/login'
import { Route as LocaleSectionRouteRouteImport } from './routes/$locale/$section/route'
import { Route as LocaleSectionIndexRouteImport } from './routes/$locale/$section/index'
import { Route as PlBazaWiedzyRssDotxmlRouteImport } from './routes/pl/baza-wiedzy/rss[.]xml'
import { Route as EnBlogRssDotxmlRouteImport } from './routes/en/blog/rss[.]xml'
import { Route as AdminOrdersShortIdRouteImport } from './routes/admin/orders.$shortId'
import { Route as LocalePaySessionIdRouteImport } from './routes/$locale/pay/$sessionId'
import { Route as LocaleOrderStatusTokenRouteImport } from './routes/$locale/order/$statusToken'
import { Route as LocaleSectionDetailRouteImport } from './routes/$locale/$section/$detail'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const AdminStepRequestsRoute = AdminStepRequestsRouteImport.update({
  id: '/step-requests',
  path: '/step-requests',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LocaleQuoteRoute = LocaleQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleOrdersRoute = LocaleOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSectionRouteRoute = LocaleSectionRouteRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSectionIndexRoute = LocaleSectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleSectionRouteRoute,
} as any)
const PlBazaWiedzyRssDotxmlRoute = PlBazaWiedzyRssDotxmlRouteImport.update({
  id: '/pl/baza-wiedzy/rss.xml',
  path: '/pl/baza-wiedzy/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogRssDotxmlRoute = EnBlogRssDotxmlRouteImport.update({
  id: '/en/blog/rss.xml',
  path: '/en/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersShortIdRoute = AdminOrdersShortIdRouteImport.update({
  id: '/orders/$shortId',
  path: '/orders/$shortId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LocalePaySessionIdRoute = LocalePaySessionIdRouteImport.update({
  id: '/pay/$sessionId',
  path: '/pay/$sessionId',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleOrderStatusTokenRoute = LocaleOrderStatusTokenRouteImport.update({
  id: '/order/$statusToken',
  path: '/order/$statusToken',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSectionDetailRoute = LocaleSectionDetailRouteImport.update({
  id: '/$detail',
  path: '/$detail',
  getParentRoute: () => LocaleSectionRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/$locale/$section': typeof LocaleSectionRouteRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/orders': typeof LocaleOrdersRoute
  '/$locale/quote': typeof LocaleQuoteRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/step-requests': typeof AdminStepRequestsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$locale/$section/$detail': typeof LocaleSectionDetailRoute
  '/$locale/order/$statusToken': typeof LocaleOrderStatusTokenRoute
  '/$locale/pay/$sessionId': typeof LocalePaySessionIdRoute
  '/admin/orders/$shortId': typeof AdminOrdersShortIdRoute
  '/en/blog/rss.xml': typeof EnBlogRssDotxmlRoute
  '/pl/baza-wiedzy/rss.xml': typeof PlBazaWiedzyRssDotxmlRoute
  '/$locale/$section/': typeof LocaleSectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/orders': typeof LocaleOrdersRoute
  '/$locale/quote': typeof LocaleQuoteRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/step-requests': typeof AdminStepRequestsRoute
  '/$locale': typeof LocaleIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$locale/$section/$detail': typeof LocaleSectionDetailRoute
  '/$locale/order/$statusToken': typeof LocaleOrderStatusTokenRoute
  '/$locale/pay/$sessionId': typeof LocalePaySessionIdRoute
  '/admin/orders/$shortId': typeof AdminOrdersShortIdRoute
  '/en/blog/rss.xml': typeof EnBlogRssDotxmlRoute
  '/pl/baza-wiedzy/rss.xml': typeof PlBazaWiedzyRssDotxmlRoute
  '/$locale/$section': typeof LocaleSectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/$locale/$section': typeof LocaleSectionRouteRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/orders': typeof LocaleOrdersRoute
  '/$locale/quote': typeof LocaleQuoteRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/step-requests': typeof AdminStepRequestsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$locale/$section/$detail': typeof LocaleSectionDetailRoute
  '/$locale/order/$statusToken': typeof LocaleOrderStatusTokenRoute
  '/$locale/pay/$sessionId': typeof LocalePaySessionIdRoute
  '/admin/orders/$shortId': typeof AdminOrdersShortIdRoute
  '/en/blog/rss.xml': typeof EnBlogRssDotxmlRoute
  '/pl/baza-wiedzy/rss.xml': typeof PlBazaWiedzyRssDotxmlRoute
  '/$locale/$section/': typeof LocaleSectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/admin'
    | '/$locale/$section'
    | '/$locale/login'
    | '/$locale/orders'
    | '/$locale/quote'
    | '/admin/customers'
    | '/admin/pricing'
    | '/admin/step-requests'
    | '/$locale/'
    | '/admin/'
    | '/$locale/$section/$detail'
    | '/$locale/order/$statusToken'
    | '/$locale/pay/$sessionId'
    | '/admin/orders/$shortId'
    | '/en/blog/rss.xml'
    | '/pl/baza-wiedzy/rss.xml'
    | '/$locale/$section/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/login'
    | '/$locale/orders'
    | '/$locale/quote'
    | '/admin/customers'
    | '/admin/pricing'
    | '/admin/step-requests'
    | '/$locale'
    | '/admin'
    | '/$locale/$section/$detail'
    | '/$locale/order/$statusToken'
    | '/$locale/pay/$sessionId'
    | '/admin/orders/$shortId'
    | '/en/blog/rss.xml'
    | '/pl/baza-wiedzy/rss.xml'
    | '/$locale/$section'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/admin'
    | '/$locale/$section'
    | '/$locale/login'
    | '/$locale/orders'
    | '/$locale/quote'
    | '/admin/customers'
    | '/admin/pricing'
    | '/admin/step-requests'
    | '/$locale/'
    | '/admin/'
    | '/$locale/$section/$detail'
    | '/$locale/order/$statusToken'
    | '/$locale/pay/$sessionId'
    | '/admin/orders/$shortId'
    | '/en/blog/rss.xml'
    | '/pl/baza-wiedzy/rss.xml'
    | '/$locale/$section/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  EnBlogRssDotxmlRoute: typeof EnBlogRssDotxmlRoute
  PlBazaWiedzyRssDotxmlRoute: typeof PlBazaWiedzyRssDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/admin/step-requests': {
      id: '/admin/step-requests'
      path: '/step-requests'
      fullPath: '/admin/step-requests'
      preLoaderRoute: typeof AdminStepRequestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$locale/quote': {
      id: '/$locale/quote'
      path: '/quote'
      fullPath: '/$locale/quote'
      preLoaderRoute: typeof LocaleQuoteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/orders': {
      id: '/$locale/orders'
      path: '/orders'
      fullPath: '/$locale/orders'
      preLoaderRoute: typeof LocaleOrdersRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/$section': {
      id: '/$locale/$section'
      path: '/$section'
      fullPath: '/$locale/$section'
      preLoaderRoute: typeof LocaleSectionRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/$section/': {
      id: '/$locale/$section/'
      path: '/'
      fullPath: '/$locale/$section/'
      preLoaderRoute: typeof LocaleSectionIndexRouteImport
      parentRoute: typeof LocaleSectionRouteRoute
    }
    '/pl/baza-wiedzy/rss.xml': {
      id: '/pl/baza-wiedzy/rss.xml'
      path: '/pl/baza-wiedzy/rss.xml'
      fullPath: '/pl/baza-wiedzy/rss.xml'
      preLoaderRoute: typeof PlBazaWiedzyRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog/rss.xml': {
      id: '/en/blog/rss.xml'
      path: '/en/blog/rss.xml'
      fullPath: '/en/blog/rss.xml'
      preLoaderRoute: typeof EnBlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$shortId': {
      id: '/admin/orders/$shortId'
      path: '/orders/$shortId'
      fullPath: '/admin/orders/$shortId'
      preLoaderRoute: typeof AdminOrdersShortIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$locale/pay/$sessionId': {
      id: '/$locale/pay/$sessionId'
      path: '/pay/$sessionId'
      fullPath: '/$locale/pay/$sessionId'
      preLoaderRoute: typeof LocalePaySessionIdRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/order/$statusToken': {
      id: '/$locale/order/$statusToken'
      path: '/order/$statusToken'
      fullPath: '/$locale/order/$statusToken'
      preLoaderRoute: typeof LocaleOrderStatusTokenRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/$section/$detail': {
      id: '/$locale/$section/$detail'
      path: '/$detail'
      fullPath: '/$locale/$section/$detail'
      preLoaderRoute: typeof LocaleSectionDetailRouteImport
      parentRoute: typeof LocaleSectionRouteRoute
    }
  }
}

interface LocaleSectionRouteRouteChildren {
  LocaleSectionDetailRoute: typeof LocaleSectionDetailRoute
  LocaleSectionIndexRoute: typeof LocaleSectionIndexRoute
}

const LocaleSectionRouteRouteChildren: LocaleSectionRouteRouteChildren = {
  LocaleSectionDetailRoute: LocaleSectionDetailRoute,
  LocaleSectionIndexRoute: LocaleSectionIndexRoute,
}

const LocaleSectionRouteRouteWithChildren =
  LocaleSectionRouteRoute._addFileChildren(LocaleSectionRouteRouteChildren)

interface LocaleRouteRouteChildren {
  LocaleSectionRouteRoute: typeof LocaleSectionRouteRouteWithChildren
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleOrdersRoute: typeof LocaleOrdersRoute
  LocaleQuoteRoute: typeof LocaleQuoteRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleOrderStatusTokenRoute: typeof LocaleOrderStatusTokenRoute
  LocalePaySessionIdRoute: typeof LocalePaySessionIdRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleSectionRouteRoute: LocaleSectionRouteRouteWithChildren,
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleOrdersRoute: LocaleOrdersRoute,
  LocaleQuoteRoute: LocaleQuoteRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleOrderStatusTokenRoute: LocaleOrderStatusTokenRoute,
  LocalePaySessionIdRoute: LocalePaySessionIdRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminStepRequestsRoute: typeof AdminStepRequestsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersShortIdRoute: typeof AdminOrdersShortIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminStepRequestsRoute: AdminStepRequestsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersShortIdRoute: AdminOrdersShortIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  EnBlogRssDotxmlRoute: EnBlogRssDotxmlRoute,
  PlBazaWiedzyRssDotxmlRoute: PlBazaWiedzyRssDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
