/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleQuoteRouteImport } from './routes/$locale/quote'
import { Route as LocaleOrdersRouteImport } from './routes/$locale/orders'
import { Route as LocaleLoginRouteImport } from './routes/$locale/login'
import { Route as LocaleSectionRouteRouteImport } from './routes/$locale/$section/route'
import { Route as LocaleSectionIndexRouteImport } from './routes/$locale/$section/index'
import { Route as PlBazaWiedzyRssDotxmlRouteImport } from './routes/pl/baza-wiedzy/rss[.]xml'
import { Route as EnBlogRssDotxmlRouteImport } from './routes/en/blog/rss[.]xml'
import { Route as LocaleSectionDetailRouteImport } from './routes/$locale/$section/$detail'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleQuoteRoute = LocaleQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleOrdersRoute = LocaleOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSectionRouteRoute = LocaleSectionRouteRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSectionIndexRoute = LocaleSectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleSectionRouteRoute,
} as any)
const PlBazaWiedzyRssDotxmlRoute = PlBazaWiedzyRssDotxmlRouteImport.update({
  id: '/pl/baza-wiedzy/rss.xml',
  path: '/pl/baza-wiedzy/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogRssDotxmlRoute = EnBlogRssDotxmlRouteImport.update({
  id: '/en/blog/rss.xml',
  path: '/en/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSectionDetailRoute = LocaleSectionDetailRouteImport.update({
  id: '/$detail',
  path: '/$detail',
  getParentRoute: () => LocaleSectionRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/$section': typeof LocaleSectionRouteRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/orders': typeof LocaleOrdersRoute
  '/$locale/quote': typeof LocaleQuoteRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$section/$detail': typeof LocaleSectionDetailRoute
  '/en/blog/rss.xml': typeof EnBlogRssDotxmlRoute
  '/pl/baza-wiedzy/rss.xml': typeof PlBazaWiedzyRssDotxmlRoute
  '/$locale/$section/': typeof LocaleSectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/orders': typeof LocaleOrdersRoute
  '/$locale/quote': typeof LocaleQuoteRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/$section/$detail': typeof LocaleSectionDetailRoute
  '/en/blog/rss.xml': typeof EnBlogRssDotxmlRoute
  '/pl/baza-wiedzy/rss.xml': typeof PlBazaWiedzyRssDotxmlRoute
  '/$locale/$section': typeof LocaleSectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/$section': typeof LocaleSectionRouteRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/orders': typeof LocaleOrdersRoute
  '/$locale/quote': typeof LocaleQuoteRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$section/$detail': typeof LocaleSectionDetailRoute
  '/en/blog/rss.xml': typeof EnBlogRssDotxmlRoute
  '/pl/baza-wiedzy/rss.xml': typeof PlBazaWiedzyRssDotxmlRoute
  '/$locale/$section/': typeof LocaleSectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/$section'
    | '/$locale/login'
    | '/$locale/orders'
    | '/$locale/quote'
    | '/$locale/'
    | '/$locale/$section/$detail'
    | '/en/blog/rss.xml'
    | '/pl/baza-wiedzy/rss.xml'
    | '/$locale/$section/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/login'
    | '/$locale/orders'
    | '/$locale/quote'
    | '/$locale'
    | '/$locale/$section/$detail'
    | '/en/blog/rss.xml'
    | '/pl/baza-wiedzy/rss.xml'
    | '/$locale/$section'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/$section'
    | '/$locale/login'
    | '/$locale/orders'
    | '/$locale/quote'
    | '/$locale/'
    | '/$locale/$section/$detail'
    | '/en/blog/rss.xml'
    | '/pl/baza-wiedzy/rss.xml'
    | '/$locale/$section/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  EnBlogRssDotxmlRoute: typeof EnBlogRssDotxmlRoute
  PlBazaWiedzyRssDotxmlRoute: typeof PlBazaWiedzyRssDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/quote': {
      id: '/$locale/quote'
      path: '/quote'
      fullPath: '/$locale/quote'
      preLoaderRoute: typeof LocaleQuoteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/orders': {
      id: '/$locale/orders'
      path: '/orders'
      fullPath: '/$locale/orders'
      preLoaderRoute: typeof LocaleOrdersRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/$section': {
      id: '/$locale/$section'
      path: '/$section'
      fullPath: '/$locale/$section'
      preLoaderRoute: typeof LocaleSectionRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/$section/': {
      id: '/$locale/$section/'
      path: '/'
      fullPath: '/$locale/$section/'
      preLoaderRoute: typeof LocaleSectionIndexRouteImport
      parentRoute: typeof LocaleSectionRouteRoute
    }
    '/pl/baza-wiedzy/rss.xml': {
      id: '/pl/baza-wiedzy/rss.xml'
      path: '/pl/baza-wiedzy/rss.xml'
      fullPath: '/pl/baza-wiedzy/rss.xml'
      preLoaderRoute: typeof PlBazaWiedzyRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog/rss.xml': {
      id: '/en/blog/rss.xml'
      path: '/en/blog/rss.xml'
      fullPath: '/en/blog/rss.xml'
      preLoaderRoute: typeof EnBlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$section/$detail': {
      id: '/$locale/$section/$detail'
      path: '/$detail'
      fullPath: '/$locale/$section/$detail'
      preLoaderRoute: typeof LocaleSectionDetailRouteImport
      parentRoute: typeof LocaleSectionRouteRoute
    }
  }
}

interface LocaleSectionRouteRouteChildren {
  LocaleSectionDetailRoute: typeof LocaleSectionDetailRoute
  LocaleSectionIndexRoute: typeof LocaleSectionIndexRoute
}

const LocaleSectionRouteRouteChildren: LocaleSectionRouteRouteChildren = {
  LocaleSectionDetailRoute: LocaleSectionDetailRoute,
  LocaleSectionIndexRoute: LocaleSectionIndexRoute,
}

const LocaleSectionRouteRouteWithChildren =
  LocaleSectionRouteRoute._addFileChildren(LocaleSectionRouteRouteChildren)

interface LocaleRouteRouteChildren {
  LocaleSectionRouteRoute: typeof LocaleSectionRouteRouteWithChildren
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleOrdersRoute: typeof LocaleOrdersRoute
  LocaleQuoteRoute: typeof LocaleQuoteRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleSectionRouteRoute: LocaleSectionRouteRouteWithChildren,
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleOrdersRoute: LocaleOrdersRoute,
  LocaleQuoteRoute: LocaleQuoteRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  EnBlogRssDotxmlRoute: EnBlogRssDotxmlRoute,
  PlBazaWiedzyRssDotxmlRoute: PlBazaWiedzyRssDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
