// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountDeletableFilesByEmail = `-- name: AdminCountDeletableFilesByEmail :one
SELECT count(DISTINCT f.id)::int FROM files f
WHERE (EXISTS (SELECT 1 FROM quote_parts qp JOIN quotes q ON q.id = qp.quote_id
               WHERE qp.file_id = f.id AND q.email = $1)
    OR EXISTS (SELECT 1 FROM order_items oi JOIN orders o ON o.id = oi.order_id
               WHERE oi.file_id = f.id AND o.email = $1)
    OR EXISTS (SELECT 1 FROM step_requests sr
               WHERE sr.file_id = f.id AND sr.email = $1))
  AND NOT EXISTS (
       SELECT 1 FROM order_items oi JOIN orders o ON o.id = oi.order_id
       WHERE oi.file_id = f.id AND o.email = $1
         AND (o.retention_until IS NOT NULL
              OR EXISTS (SELECT 1 FROM invoices i WHERE i.order_id = o.id)))
`

// Files the email touches that no retained order needs.
func (q *Queries) AdminCountDeletableFilesByEmail(ctx context.Context, email *string) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountDeletableFilesByEmail, email)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountInvoicesByEmail = `-- name: AdminCountInvoicesByEmail :one
SELECT count(*)::int FROM invoices i JOIN orders o ON o.id = i.order_id
WHERE o.email = $1
`

func (q *Queries) AdminCountInvoicesByEmail(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountInvoicesByEmail, email)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountNewStepRequests = `-- name: AdminCountNewStepRequests :one
SELECT count(*)::int FROM step_requests WHERE status = 'new'
`

func (q *Queries) AdminCountNewStepRequests(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountNewStepRequests)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountOrderItemsByRetention = `-- name: AdminCountOrderItemsByRetention :one
SELECT count(*)::int FROM order_items oi JOIN orders o ON o.id = oi.order_id
WHERE o.email = $1
  AND (o.retention_until IS NOT NULL
       OR EXISTS (SELECT 1 FROM invoices i WHERE i.order_id = o.id)) = $2::boolean
`

type AdminCountOrderItemsByRetentionParams struct {
	Email    string
	Retained bool
}

func (q *Queries) AdminCountOrderItemsByRetention(ctx context.Context, arg AdminCountOrderItemsByRetentionParams) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountOrderItemsByRetention, arg.Email, arg.Retained)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountOrders = `-- name: AdminCountOrders :one
SELECT count(*)::int FROM orders o
WHERE ($1::text IS NULL OR o.status = $1::text)
`

func (q *Queries) AdminCountOrders(ctx context.Context, status *string) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountOrders, status)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountOrdersByRetention = `-- name: AdminCountOrdersByRetention :one
SELECT count(*)::int FROM orders o
WHERE o.email = $1
  AND (o.retention_until IS NOT NULL
       OR EXISTS (SELECT 1 FROM invoices i WHERE i.order_id = o.id)) = $2::boolean
`

type AdminCountOrdersByRetentionParams struct {
	Email    string
	Retained bool
}

func (q *Queries) AdminCountOrdersByRetention(ctx context.Context, arg AdminCountOrdersByRetentionParams) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountOrdersByRetention, arg.Email, arg.Retained)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountPaymentsByRetention = `-- name: AdminCountPaymentsByRetention :one
SELECT count(*)::int FROM payments p JOIN orders o ON o.id = p.order_id
WHERE o.email = $1
  AND (o.retention_until IS NOT NULL
       OR EXISTS (SELECT 1 FROM invoices i WHERE i.order_id = o.id)) = $2::boolean
`

type AdminCountPaymentsByRetentionParams struct {
	Email    string
	Retained bool
}

func (q *Queries) AdminCountPaymentsByRetention(ctx context.Context, arg AdminCountPaymentsByRetentionParams) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountPaymentsByRetention, arg.Email, arg.Retained)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountQuotePartsByEmail = `-- name: AdminCountQuotePartsByEmail :one
SELECT count(*)::int FROM quote_parts qp JOIN quotes q ON q.id = qp.quote_id
WHERE q.email = $1
`

func (q *Queries) AdminCountQuotePartsByEmail(ctx context.Context, email *string) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountQuotePartsByEmail, email)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountQuotesByEmail = `-- name: AdminCountQuotesByEmail :one
SELECT count(*)::int FROM quotes WHERE email = $1
`

func (q *Queries) AdminCountQuotesByEmail(ctx context.Context, email *string) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountQuotesByEmail, email)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountRetainedFilesByEmail = `-- name: AdminCountRetainedFilesByEmail :one
SELECT count(DISTINCT f.id)::int FROM files f
JOIN order_items oi ON oi.file_id = f.id
JOIN orders o ON o.id = oi.order_id
WHERE o.email = $1
  AND (o.retention_until IS NOT NULL
       OR EXISTS (SELECT 1 FROM invoices i WHERE i.order_id = o.id))
`

func (q *Queries) AdminCountRetainedFilesByEmail(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountRetainedFilesByEmail, email)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountSessionsByEmail = `-- name: AdminCountSessionsByEmail :one
SELECT count(*)::int FROM sessions s JOIN users u ON u.id = s.user_id
WHERE u.email = $1
`

func (q *Queries) AdminCountSessionsByEmail(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountSessionsByEmail, email)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountStepRequestsByEmail = `-- name: AdminCountStepRequestsByEmail :one
SELECT count(*)::int FROM step_requests WHERE email = $1
`

func (q *Queries) AdminCountStepRequestsByEmail(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountStepRequestsByEmail, email)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountUserByEmail = `-- name: AdminCountUserByEmail :one
SELECT count(*)::int FROM users WHERE email = $1
`

// Erase dry-run counts. Retained = the invoice-retention carve-out (plan 09):
// the order has retention_until set OR any invoice row.
func (q *Queries) AdminCountUserByEmail(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountUserByEmail, email)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminListFilesByEmail = `-- name: AdminListFilesByEmail :many
SELECT DISTINCT f.id, f.file_name, f.kind, f.file_size_bytes,
       (f.storage_key IS NOT NULL)::boolean AS stored, f.created_at
FROM files f
WHERE f.deleted_at IS NULL
  AND (EXISTS (SELECT 1 FROM quote_parts qp JOIN quotes q ON q.id = qp.quote_id
               WHERE qp.file_id = f.id AND q.email = $1)
    OR EXISTS (SELECT 1 FROM order_items oi JOIN orders o ON o.id = oi.order_id
               WHERE oi.file_id = f.id AND o.email = $1)
    OR EXISTS (SELECT 1 FROM step_requests sr
               WHERE sr.file_id = f.id AND sr.email = $1))
ORDER BY f.created_at DESC
`

type AdminListFilesByEmailRow struct {
	ID            uuid.UUID
	FileName      string
	Kind          string
	FileSizeBytes int64
	Stored        bool
	CreatedAt     pgtype.Timestamptz
}

// Files linked to the email via any of the three attach points (quote parts,
// order items, STEP requests), deduplicated.
func (q *Queries) AdminListFilesByEmail(ctx context.Context, email *string) ([]AdminListFilesByEmailRow, error) {
	rows, err := q.db.Query(ctx, adminListFilesByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListFilesByEmailRow
	for rows.Next() {
		var i AdminListFilesByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.Kind,
			&i.FileSizeBytes,
			&i.Stored,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOpenOrders = `-- name: AdminListOpenOrders :many
SELECT o.short_id, o.email, o.status, o.gross_total_grosze, o.created_at,
       o.paid_at, o.tracking_number,
       (SELECT count(*) FROM order_items i WHERE i.order_id = o.id)::int AS part_count,
       (SELECT coalesce(array_agg(DISTINCT i.lead_time), '{}'::text[])
          FROM order_items i WHERE i.order_id = o.id)::text[] AS lead_times,
       (SELECT coalesce(array_agg(DISTINCT f ->> 'code'), '{}'::text[])
          FROM order_items i,
               jsonb_array_elements(i.part_quote_snapshot -> 'dfmFlags') f
          WHERE i.order_id = o.id
            AND ((f ->> 'severity') IN ('warn', 'block')
                 OR (f ->> 'code') = 'manual_verify'))::text[] AS dfm_codes
FROM orders o
WHERE o.status IN ('paid', 'in_production')
ORDER BY o.created_at DESC
`

type AdminListOpenOrdersRow struct {
	ShortID          string
	Email            string
	Status           string
	GrossTotalGrosze int32
	CreatedAt        pgtype.Timestamptz
	PaidAt           pgtype.Timestamptz
	TrackingNumber   *string
	PartCount        int32
	LeadTimes        []string
	DfmCodes         []string
}

// Ops view input: orders being actively fulfilled (paid + in_production),
// the enriched board shape. The Go side derives ship-by and filters due ones.
func (q *Queries) AdminListOpenOrders(ctx context.Context) ([]AdminListOpenOrdersRow, error) {
	rows, err := q.db.Query(ctx, adminListOpenOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOpenOrdersRow
	for rows.Next() {
		var i AdminListOpenOrdersRow
		if err := rows.Scan(
			&i.ShortID,
			&i.Email,
			&i.Status,
			&i.GrossTotalGrosze,
			&i.CreatedAt,
			&i.PaidAt,
			&i.TrackingNumber,
			&i.PartCount,
			&i.LeadTimes,
			&i.DfmCodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOrders = `-- name: AdminListOrders :many
SELECT o.short_id, o.email, o.status, o.gross_total_grosze, o.created_at,
       o.paid_at, o.tracking_number,
       (SELECT count(*) FROM order_items i WHERE i.order_id = o.id)::int AS part_count,
       (SELECT coalesce(array_agg(DISTINCT i.lead_time), '{}'::text[])
          FROM order_items i WHERE i.order_id = o.id)::text[] AS lead_times,
       (SELECT coalesce(array_agg(DISTINCT f ->> 'code'), '{}'::text[])
          FROM order_items i,
               jsonb_array_elements(i.part_quote_snapshot -> 'dfmFlags') f
          WHERE i.order_id = o.id
            AND ((f ->> 'severity') IN ('warn', 'block')
                 OR (f ->> 'code') = 'manual_verify'))::text[] AS dfm_codes
FROM orders o
WHERE ($1::text IS NULL OR o.status = $1::text)
ORDER BY o.created_at DESC
LIMIT $3 OFFSET $2
`

type AdminListOrdersParams struct {
	Status    *string
	RowOffset int32
	RowLimit  int32
}

type AdminListOrdersRow struct {
	ShortID          string
	Email            string
	Status           string
	GrossTotalGrosze int32
	CreatedAt        pgtype.Timestamptz
	PaidAt           pgtype.Timestamptz
	TrackingNumber   *string
	PartCount        int32
	LeadTimes        []string
	DfmCodes         []string
}

// Orders board: every order, newest first, optionally filtered by status.
// lead_times feeds the Go-side ship-by derivation (lead-time engine with
// paid_at as anchor); dfm_codes flags orders carrying a warn/block flag or
// plan 02's manual_verify code (code-agnostic — the severity predicate alone
// flags today's DFM codes).
func (q *Queries) AdminListOrders(ctx context.Context, arg AdminListOrdersParams) ([]AdminListOrdersRow, error) {
	rows, err := q.db.Query(ctx, adminListOrders, arg.Status, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOrdersRow
	for rows.Next() {
		var i AdminListOrdersRow
		if err := rows.Scan(
			&i.ShortID,
			&i.Email,
			&i.Status,
			&i.GrossTotalGrosze,
			&i.CreatedAt,
			&i.PaidAt,
			&i.TrackingNumber,
			&i.PartCount,
			&i.LeadTimes,
			&i.DfmCodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOrdersByEmail = `-- name: AdminListOrdersByEmail :many
SELECT o.short_id, o.email, o.status, o.gross_total_grosze, o.created_at,
       o.paid_at, o.tracking_number,
       (SELECT count(*) FROM order_items i WHERE i.order_id = o.id)::int AS part_count,
       (SELECT coalesce(array_agg(DISTINCT i.lead_time), '{}'::text[])
          FROM order_items i WHERE i.order_id = o.id)::text[] AS lead_times,
       (SELECT coalesce(array_agg(DISTINCT f ->> 'code'), '{}'::text[])
          FROM order_items i,
               jsonb_array_elements(i.part_quote_snapshot -> 'dfmFlags') f
          WHERE i.order_id = o.id
            AND ((f ->> 'severity') IN ('warn', 'block')
                 OR (f ->> 'code') = 'manual_verify'))::text[] AS dfm_codes
FROM orders o
WHERE o.email = $1
ORDER BY o.created_at DESC
LIMIT 200
`

type AdminListOrdersByEmailRow struct {
	ShortID          string
	Email            string
	Status           string
	GrossTotalGrosze int32
	CreatedAt        pgtype.Timestamptz
	PaidAt           pgtype.Timestamptz
	TrackingNumber   *string
	PartCount        int32
	LeadTimes        []string
	DfmCodes         []string
}

// Customer lookup: the board's enriched shape filtered to one email (guest
// orders included — email is the join key). Uses the orders_email index.
func (q *Queries) AdminListOrdersByEmail(ctx context.Context, email string) ([]AdminListOrdersByEmailRow, error) {
	rows, err := q.db.Query(ctx, adminListOrdersByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOrdersByEmailRow
	for rows.Next() {
		var i AdminListOrdersByEmailRow
		if err := rows.Scan(
			&i.ShortID,
			&i.Email,
			&i.Status,
			&i.GrossTotalGrosze,
			&i.CreatedAt,
			&i.PaidAt,
			&i.TrackingNumber,
			&i.PartCount,
			&i.LeadTimes,
			&i.DfmCodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminStatsByStatus = `-- name: AdminStatsByStatus :many
SELECT o.status, count(*)::int AS count
FROM orders o
GROUP BY o.status
`

type AdminStatsByStatusRow struct {
	Status string
	Count  int32
}

// Board pills: every order status with its count.
func (q *Queries) AdminStatsByStatus(ctx context.Context) ([]AdminStatsByStatusRow, error) {
	rows, err := q.db.Query(ctx, adminStatsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminStatsByStatusRow
	for rows.Next() {
		var i AdminStatsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminStatsDaily = `-- name: AdminStatsDaily :many
SELECT to_char(o.created_at AT TIME ZONE 'Europe/Warsaw', 'YYYY-MM-DD') AS day,
       count(*)::int AS orders,
       coalesce(sum(o.gross_total_grosze), 0)::bigint AS gross_grosze
FROM orders o
WHERE o.created_at >= ((now() AT TIME ZONE 'Europe/Warsaw')::date - 14)::timestamptz
GROUP BY 1
ORDER BY 1
`

type AdminStatsDailyRow struct {
	Day         string
	Orders      int32
	GrossGrosze int64
}

// KPI strip input: per-day order counts + gross on the Warsaw calendar,
// covering today and the 14 lookback days (the Go side zero-fills).
func (q *Queries) AdminStatsDaily(ctx context.Context) ([]AdminStatsDailyRow, error) {
	rows, err := q.db.Query(ctx, adminStatsDaily)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminStatsDailyRow
	for rows.Next() {
		var i AdminStatsDailyRow
		if err := rows.Scan(&i.Day, &i.Orders, &i.GrossGrosze); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderFileForDownload = `-- name: GetOrderFileForDownload :one
SELECT f.id, f.file_name, f.file_size_bytes, f.kind, f.storage_key
FROM files f
JOIN order_items i ON i.file_id = f.id
JOIN orders o ON o.id = i.order_id
WHERE o.short_id = $1 AND f.id = $2 AND f.deleted_at IS NULL
`

type GetOrderFileForDownloadParams struct {
	ShortID string
	ID      uuid.UUID
}

type GetOrderFileForDownloadRow struct {
	ID            uuid.UUID
	FileName      string
	FileSizeBytes int64
	Kind          string
	StorageKey    *string
}

// The admin download gate: the file must be attached to THIS order (and not
// soft-deleted) — a foreign file id is a 404, never a leak.
func (q *Queries) GetOrderFileForDownload(ctx context.Context, arg GetOrderFileForDownloadParams) (GetOrderFileForDownloadRow, error) {
	row := q.db.QueryRow(ctx, getOrderFileForDownload, arg.ShortID, arg.ID)
	var i GetOrderFileForDownloadRow
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileSizeBytes,
		&i.Kind,
		&i.StorageKey,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, role, created_at FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID        uuid.UUID
	Email     string
	Role      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listInvoicesByOrderID = `-- name: ListInvoicesByOrderID :many
SELECT id, order_id, provider_id, number, pdf_url, pdf_storage_key, kind, issued_at, retention_until, created_at FROM invoices WHERE order_id = $1 ORDER BY created_at
`

func (q *Queries) ListInvoicesByOrderID(ctx context.Context, orderID uuid.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProviderID,
			&i.Number,
			&i.PdfUrl,
			&i.PdfStorageKey,
			&i.Kind,
			&i.IssuedAt,
			&i.RetentionUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByOrderID = `-- name: ListPaymentsByOrderID :many
SELECT id, order_id, provider, provider_event_id, payment_ref, type, amount_grosze, status, raw, created_at FROM payments WHERE order_id = $1 ORDER BY created_at
`

func (q *Queries) ListPaymentsByOrderID(ctx context.Context, orderID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Provider,
			&i.ProviderEventID,
			&i.PaymentRef,
			&i.Type,
			&i.AmountGrosze,
			&i.Status,
			&i.Raw,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepRequestsByEmail = `-- name: ListStepRequestsByEmail :many
SELECT id, short_id, email, file_name, file_size_bytes, file_id, status, created_at FROM step_requests WHERE email = $1 ORDER BY created_at DESC LIMIT 200
`

func (q *Queries) ListStepRequestsByEmail(ctx context.Context, email string) ([]StepRequest, error) {
	rows, err := q.db.Query(ctx, listStepRequestsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StepRequest
	for rows.Next() {
		var i StepRequest
		if err := rows.Scan(
			&i.ID,
			&i.ShortID,
			&i.Email,
			&i.FileName,
			&i.FileSizeBytes,
			&i.FileID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderCancelled = `-- name: MarkOrderCancelled :execrows
UPDATE orders SET status = 'cancelled', updated_at = now()
WHERE id = $1 AND status IN ('draft', 'paid', 'in_production', 'shipped')
`

// Cancel is allowed from every non-terminal state (internal/orders/status.go).
func (q *Queries) MarkOrderCancelled(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markOrderCancelled, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOrderDelivered = `-- name: MarkOrderDelivered :execrows
UPDATE orders SET status = 'delivered', updated_at = now()
WHERE id = $1 AND status = 'shipped'
`

func (q *Queries) MarkOrderDelivered(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markOrderDelivered, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOrderInProduction = `-- name: MarkOrderInProduction :execrows
UPDATE orders SET status = 'in_production', updated_at = now()
WHERE id = $1 AND status = 'paid'
`

// SQL-guarded like MarkOrderPaid: 0 rows means a race already moved the order.
func (q *Queries) MarkOrderInProduction(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markOrderInProduction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOrderShipped = `-- name: MarkOrderShipped :execrows
UPDATE orders SET status = 'shipped', tracking_number = $2, updated_at = now()
WHERE id = $1 AND status = 'in_production'
`

type MarkOrderShippedParams struct {
	ID             uuid.UUID
	TrackingNumber *string
}

func (q *Queries) MarkOrderShipped(ctx context.Context, arg MarkOrderShippedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOrderShipped, arg.ID, arg.TrackingNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
