// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: admin.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountOrders = `-- name: AdminCountOrders :one
SELECT count(*)::int FROM orders o
WHERE ($1::text IS NULL OR o.status = $1::text)
`

func (q *Queries) AdminCountOrders(ctx context.Context, status *string) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountOrders, status)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminListOrders = `-- name: AdminListOrders :many
SELECT o.short_id, o.email, o.status, o.gross_total_grosze, o.created_at,
       o.paid_at, o.tracking_number,
       (SELECT count(*) FROM order_items i WHERE i.order_id = o.id)::int AS part_count,
       (SELECT coalesce(array_agg(DISTINCT i.lead_time), '{}'::text[])
          FROM order_items i WHERE i.order_id = o.id)::text[] AS lead_times,
       (SELECT coalesce(array_agg(DISTINCT f ->> 'code'), '{}'::text[])
          FROM order_items i,
               jsonb_array_elements(i.part_quote_snapshot -> 'dfmFlags') f
          WHERE i.order_id = o.id
            AND ((f ->> 'severity') IN ('warn', 'block')
                 OR (f ->> 'code') = 'manual_verify'))::text[] AS dfm_codes
FROM orders o
WHERE ($1::text IS NULL OR o.status = $1::text)
ORDER BY o.created_at DESC
LIMIT $3 OFFSET $2
`

type AdminListOrdersParams struct {
	Status    *string
	RowOffset int32
	RowLimit  int32
}

type AdminListOrdersRow struct {
	ShortID          string
	Email            string
	Status           string
	GrossTotalGrosze int32
	CreatedAt        pgtype.Timestamptz
	PaidAt           pgtype.Timestamptz
	TrackingNumber   *string
	PartCount        int32
	LeadTimes        []string
	DfmCodes         []string
}

// Orders board: every order, newest first, optionally filtered by status.
// lead_times feeds the Go-side ship-by derivation (lead-time engine with
// paid_at as anchor); dfm_codes flags orders carrying a warn/block flag or
// plan 02's manual_verify code (code-agnostic — the severity predicate alone
// flags today's DFM codes).
func (q *Queries) AdminListOrders(ctx context.Context, arg AdminListOrdersParams) ([]AdminListOrdersRow, error) {
	rows, err := q.db.Query(ctx, adminListOrders, arg.Status, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOrdersRow
	for rows.Next() {
		var i AdminListOrdersRow
		if err := rows.Scan(
			&i.ShortID,
			&i.Email,
			&i.Status,
			&i.GrossTotalGrosze,
			&i.CreatedAt,
			&i.PaidAt,
			&i.TrackingNumber,
			&i.PartCount,
			&i.LeadTimes,
			&i.DfmCodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByOrderID = `-- name: ListInvoicesByOrderID :many
SELECT id, order_id, provider_id, number, pdf_url, pdf_storage_key, kind, issued_at, retention_until, created_at FROM invoices WHERE order_id = $1 ORDER BY created_at
`

func (q *Queries) ListInvoicesByOrderID(ctx context.Context, orderID uuid.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProviderID,
			&i.Number,
			&i.PdfUrl,
			&i.PdfStorageKey,
			&i.Kind,
			&i.IssuedAt,
			&i.RetentionUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByOrderID = `-- name: ListPaymentsByOrderID :many
SELECT id, order_id, provider, provider_event_id, payment_ref, type, amount_grosze, status, raw, created_at FROM payments WHERE order_id = $1 ORDER BY created_at
`

func (q *Queries) ListPaymentsByOrderID(ctx context.Context, orderID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Provider,
			&i.ProviderEventID,
			&i.PaymentRef,
			&i.Type,
			&i.AmountGrosze,
			&i.Status,
			&i.Raw,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
