// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bumpLoginCodeAttempts = `-- name: BumpLoginCodeAttempts :exec
UPDATE login_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) BumpLoginCodeAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, bumpLoginCodeAttempts, id)
	return err
}

const consumeLoginCode = `-- name: ConsumeLoginCode :exec
UPDATE login_codes SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumeLoginCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeLoginCode, id)
	return err
}

const countRecentLoginCodesForEmail = `-- name: CountRecentLoginCodesForEmail :one
SELECT count(*)::int FROM login_codes
WHERE email = $1 AND created_at > $2
`

type CountRecentLoginCodesForEmailParams struct {
	Email     string
	CreatedAt pgtype.Timestamptz
}

// Resend throttle input: codes minted in the trailing window (≤5/hour cap).
func (q *Queries) CountRecentLoginCodesForEmail(ctx context.Context, arg CountRecentLoginCodesForEmailParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRecentLoginCodesForEmail, arg.Email, arg.CreatedAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createLoginCode = `-- name: CreateLoginCode :one
INSERT INTO login_codes (email, code_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateLoginCodeParams struct {
	Email     string
	CodeHash  string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateLoginCode(ctx context.Context, arg CreateLoginCodeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createLoginCode, arg.Email, arg.CodeHash, arg.ExpiresAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateSessionParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredLoginCodes = `-- name: DeleteExpiredLoginCodes :exec
DELETE FROM login_codes WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredLoginCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredLoginCodes)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const getLatestLoginCode = `-- name: GetLatestLoginCode :one
SELECT id, email, code_hash, expires_at, attempts, consumed_at, created_at FROM login_codes
WHERE email = $1 AND consumed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

// The newest unconsumed code for the email (any expiry) — the only one
// verify-code will accept. Expiry is checked in Go so the handler can
// distinguish code_expired from code_invalid.
func (q *Queries) GetLatestLoginCode(ctx context.Context, email string) (LoginCode, error) {
	row := q.db.QueryRow(ctx, getLatestLoginCode, email)
	var i LoginCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id AS session_id, s.expires_at, s.last_seen_at,
       u.id AS user_id, u.email, u.role
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionByTokenHashRow struct {
	SessionID  uuid.UUID
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	UserID     uuid.UUID
	Email      string
	Role       string
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.UserID,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const invalidateLoginCodesForEmail = `-- name: InvalidateLoginCodesForEmail :exec
UPDATE login_codes SET consumed_at = now()
WHERE email = $1 AND consumed_at IS NULL
`

// RequestCode consumes every still-active code for the email before minting
// a new one (single active code per email).
func (q *Queries) InvalidateLoginCodesForEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, invalidateLoginCodesForEmail, email)
	return err
}

const setUserRoleByEmail = `-- name: SetUserRoleByEmail :execrows
UPDATE users SET role = $2, updated_at = now() WHERE email = $1
`

type SetUserRoleByEmailParams struct {
	Email string
	Role  string
}

// api promote-admin: the only role-escalation path (SQL-only by design; the
// 0-rows case means the email has never verified a login code).
func (q *Queries) SetUserRoleByEmail(ctx context.Context, arg SetUserRoleByEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserRoleByEmail, arg.Email, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now(), expires_at = $2 WHERE id = $1
`

type TouchSessionParams struct {
	ID        uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

// Sliding refresh, throttled ~1/hour by the caller.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}

const upsertUserByEmail = `-- name: UpsertUserByEmail :one
INSERT INTO users (email)
VALUES ($1)
ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email
RETURNING id, role
`

type UpsertUserByEmailRow struct {
	ID   uuid.UUID
	Role string
}

// Identity anchor, created on successful verify (never on code request).
func (q *Queries) UpsertUserByEmail(ctx context.Context, email string) (UpsertUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, upsertUserByEmail, email)
	var i UpsertUserByEmailRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}
