// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: email_log.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const hasSentEmail = `-- name: HasSentEmail :one
SELECT EXISTS (
    SELECT 1 FROM email_log WHERE dedupe_key = $1 AND status = 'sent'
)
`

// Dedupe check before sending: true when a prior send under this key already
// succeeded (the partial unique index email_log_dedupe_sent backstops races).
func (q *Queries) HasSentEmail(ctx context.Context, dedupeKey *string) (bool, error) {
	row := q.db.QueryRow(ctx, hasSentEmail, dedupeKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertEmailLog = `-- name: InsertEmailLog :exec
INSERT INTO email_log (
    dedupe_key, to_addr, template, locale, status,
    provider_message_id, error, order_id, user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertEmailLogParams struct {
	DedupeKey         *string
	ToAddr            string
	Template          string
	Locale            string
	Status            string
	ProviderMessageID *string
	Error             *string
	OrderID           *uuid.UUID
	UserID            *uuid.UUID
}

func (q *Queries) InsertEmailLog(ctx context.Context, arg InsertEmailLogParams) error {
	_, err := q.db.Exec(ctx, insertEmailLog,
		arg.DedupeKey,
		arg.ToAddr,
		arg.Template,
		arg.Locale,
		arg.Status,
		arg.ProviderMessageID,
		arg.Error,
		arg.OrderID,
		arg.UserID,
	)
	return err
}
