// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: files.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFileByID = `-- name: GetFileByID :one
SELECT id, user_id, file_name, file_size_bytes, kind, hash, storage_key, metrics, source, source_ref, expires_at, deleted_at, created_at FROM files WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.FileSizeBytes,
		&i.Kind,
		&i.Hash,
		&i.StorageKey,
		&i.Metrics,
		&i.Source,
		&i.SourceRef,
		&i.ExpiresAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadedFileBySha256 = `-- name: GetUploadedFileBySha256 :one
SELECT id, kind FROM files
WHERE hash = $1 AND storage_key IS NOT NULL AND deleted_at IS NULL
LIMIT 1
`

type GetUploadedFileBySha256Row struct {
	ID   uuid.UUID
	Kind string
}

func (q *Queries) GetUploadedFileBySha256(ctx context.Context, hash *string) (GetUploadedFileBySha256Row, error) {
	row := q.db.QueryRow(ctx, getUploadedFileBySha256, hash)
	var i GetUploadedFileBySha256Row
	err := row.Scan(&i.ID, &i.Kind)
	return i, err
}

const insertFile = `-- name: InsertFile :one
INSERT INTO files (file_name, file_size_bytes, kind, hash, source, source_ref, storage_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertFileParams struct {
	FileName      string
	FileSizeBytes int64
	Kind          string
	Hash          *string
	Source        string
	SourceRef     []byte
	StorageKey    *string
}

// storage_key is NULL for browser presigned uploads (set later by confirm) and
// non-NULL for the MakerWorld server-side tee (stored before the row exists).
func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertFile,
		arg.FileName,
		arg.FileSizeBytes,
		arg.Kind,
		arg.Hash,
		arg.Source,
		arg.SourceRef,
		arg.StorageKey,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listStalePendingFiles = `-- name: ListStalePendingFiles :many
SELECT id FROM files
WHERE storage_key IS NULL AND deleted_at IS NULL AND created_at < $1
`

// Uploads that reserved a row but never confirmed (no object to remove).
func (q *Queries) ListStalePendingFiles(ctx context.Context, createdAt pgtype.Timestamptz) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStalePendingFiles, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreferencedUploadedFiles = `-- name: ListUnreferencedUploadedFiles :many
SELECT files.id, files.storage_key FROM files
WHERE files.storage_key IS NOT NULL
  AND files.deleted_at IS NULL
  AND files.created_at < $1
  AND NOT EXISTS (SELECT 1 FROM quote_parts WHERE quote_parts.file_id = files.id)
  AND NOT EXISTS (SELECT 1 FROM step_requests WHERE step_requests.file_id = files.id)
`

type ListUnreferencedUploadedFilesRow struct {
	ID         uuid.UUID
	StorageKey *string
}

// Stored files past the retention window, not referenced by any quote/step row.
func (q *Queries) ListUnreferencedUploadedFiles(ctx context.Context, createdAt pgtype.Timestamptz) ([]ListUnreferencedUploadedFilesRow, error) {
	rows, err := q.db.Query(ctx, listUnreferencedUploadedFiles, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnreferencedUploadedFilesRow
	for rows.Next() {
		var i ListUnreferencedUploadedFilesRow
		if err := rows.Scan(&i.ID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFileMetrics = `-- name: SetFileMetrics :exec
UPDATE files SET metrics = $2 WHERE id = $1
`

type SetFileMetricsParams struct {
	ID      uuid.UUID
	Metrics []byte
}

// Persist the server-recomputed MeshMetrics for a stored file (plan 02).
func (q *Queries) SetFileMetrics(ctx context.Context, arg SetFileMetricsParams) error {
	_, err := q.db.Exec(ctx, setFileMetrics, arg.ID, arg.Metrics)
	return err
}

const setFileStorageKey = `-- name: SetFileStorageKey :exec
UPDATE files SET storage_key = $2 WHERE id = $1
`

type SetFileStorageKeyParams struct {
	ID         uuid.UUID
	StorageKey *string
}

func (q *Queries) SetFileStorageKey(ctx context.Context, arg SetFileStorageKeyParams) error {
	_, err := q.db.Exec(ctx, setFileStorageKey, arg.ID, arg.StorageKey)
	return err
}

const softDeleteFile = `-- name: SoftDeleteFile :exec
UPDATE files SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteFile, id)
	return err
}
