// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID            uuid.UUID
	UserID        *uuid.UUID
	FileName      string
	FileSizeBytes int64
	Kind          string
	Hash          *string
	StorageKey    *string
	Metrics       []byte
	Source        string
	SourceRef     []byte
	ExpiresAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type LoginCode struct {
	ID         uuid.UUID
	Email      string
	CodeHash   string
	ExpiresAt  pgtype.Timestamptz
	Attempts   int32
	ConsumedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Order struct {
	ID               uuid.UUID
	ShortID          string
	QuoteID          uuid.UUID
	UserID           *uuid.UUID
	Email            string
	Status           string
	GrossTotalGrosze int32
	VatGrosze        int32
	PricingConfigID  uuid.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type PricingConfigSnapshot struct {
	ID        uuid.UUID
	Label     string
	Config    []byte
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type Quote struct {
	ID                  uuid.UUID
	ShortID             string
	UserID              *uuid.UUID
	Email               *string
	Country             *string
	Status              string
	PricesExVat         bool
	PricingConfigID     uuid.UUID
	PartsSubtotalGrosze int32
	MinOrderTopupGrosze int32
	OrderFeeGrosze      int32
	ShippingGrosze      int32
	NetTotalGrosze      int32
	VatGrosze           int32
	GrossTotalGrosze    int32
	FreeShipping        bool
	MinOrderApplied     bool
	ExpiresAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Locale              string
}

type QuotePart struct {
	ID                uuid.UUID
	QuoteID           uuid.UUID
	FileID            *uuid.UUID
	FileName          string
	Hash              string
	Process           string
	Quantity          int32
	LeadTime          string
	UnitPriceGrosze   int32
	LineTotalGrosze   int32
	BillableVolumeCm3 *float64
	PieceCount        *int32
	Plates            *int32
	Breakdown         []byte
	DfmFlags          []byte
	CreatedAt         pgtype.Timestamptz
}

type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

type StepRequest struct {
	ID            uuid.UUID
	ShortID       string
	Email         string
	FileName      string
	FileSizeBytes int64
	FileID        *uuid.UUID
	Status        string
	CreatedAt     pgtype.Timestamptz
}

type User struct {
	ID          uuid.UUID
	Email       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Role        string
	CompanyName *string
	Nip         *string
}
