// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countStoredFilesByIDs = `-- name: CountStoredFilesByIDs :one
SELECT count(*) FROM files
WHERE id = ANY($1::uuid[]) AND storage_key IS NOT NULL AND deleted_at IS NULL
`

// Order-creation gate: every part's file must be uploaded (storage_key set)
// and not soft-deleted. The handler compares this count against the number of
// distinct file ids on the quote's parts.
func (q *Queries) CountStoredFilesByIDs(ctx context.Context, dollar_1 []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStoredFilesByIDs, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOrderByCheckoutSessionID = `-- name: GetOrderByCheckoutSessionID :one
SELECT id, short_id, quote_id, user_id, email, status, gross_total_grosze, vat_grosze, pricing_config_id, created_at, updated_at, pricing_snapshot, locale, country, company_name, nip, invoice_requested, shipping_address, billing_address, status_token, checkout_session_id, checkout_session_url, checkout_session_expires_at, payment_ref, retention_until, paid_at FROM orders WHERE checkout_session_id = $1
`

func (q *Queries) GetOrderByCheckoutSessionID(ctx context.Context, checkoutSessionID *string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByCheckoutSessionID, checkoutSessionID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.QuoteID,
		&i.UserID,
		&i.Email,
		&i.Status,
		&i.GrossTotalGrosze,
		&i.VatGrosze,
		&i.PricingConfigID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PricingSnapshot,
		&i.Locale,
		&i.Country,
		&i.CompanyName,
		&i.Nip,
		&i.InvoiceRequested,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.StatusToken,
		&i.CheckoutSessionID,
		&i.CheckoutSessionUrl,
		&i.CheckoutSessionExpiresAt,
		&i.PaymentRef,
		&i.RetentionUntil,
		&i.PaidAt,
	)
	return i, err
}

const getOrderByShortID = `-- name: GetOrderByShortID :one
SELECT id, short_id, quote_id, user_id, email, status, gross_total_grosze, vat_grosze, pricing_config_id, created_at, updated_at, pricing_snapshot, locale, country, company_name, nip, invoice_requested, shipping_address, billing_address, status_token, checkout_session_id, checkout_session_url, checkout_session_expires_at, payment_ref, retention_until, paid_at FROM orders WHERE short_id = $1
`

func (q *Queries) GetOrderByShortID(ctx context.Context, shortID string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByShortID, shortID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.QuoteID,
		&i.UserID,
		&i.Email,
		&i.Status,
		&i.GrossTotalGrosze,
		&i.VatGrosze,
		&i.PricingConfigID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PricingSnapshot,
		&i.Locale,
		&i.Country,
		&i.CompanyName,
		&i.Nip,
		&i.InvoiceRequested,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.StatusToken,
		&i.CheckoutSessionID,
		&i.CheckoutSessionUrl,
		&i.CheckoutSessionExpiresAt,
		&i.PaymentRef,
		&i.RetentionUntil,
		&i.PaidAt,
	)
	return i, err
}

const getOrderByStatusToken = `-- name: GetOrderByStatusToken :one
SELECT id, short_id, quote_id, user_id, email, status, gross_total_grosze, vat_grosze, pricing_config_id, created_at, updated_at, pricing_snapshot, locale, country, company_name, nip, invoice_requested, shipping_address, billing_address, status_token, checkout_session_id, checkout_session_url, checkout_session_expires_at, payment_ref, retention_until, paid_at FROM orders WHERE status_token = $1
`

func (q *Queries) GetOrderByStatusToken(ctx context.Context, statusToken string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByStatusToken, statusToken)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.QuoteID,
		&i.UserID,
		&i.Email,
		&i.Status,
		&i.GrossTotalGrosze,
		&i.VatGrosze,
		&i.PricingConfigID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PricingSnapshot,
		&i.Locale,
		&i.Country,
		&i.CompanyName,
		&i.Nip,
		&i.InvoiceRequested,
		&i.ShippingAddress,
		&i.BillingAddress,
		&i.StatusToken,
		&i.CheckoutSessionID,
		&i.CheckoutSessionUrl,
		&i.CheckoutSessionExpiresAt,
		&i.PaymentRef,
		&i.RetentionUntil,
		&i.PaidAt,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT id, order_id, file_id, file_name, hash, process, quantity, lead_time, unit_price_grosze, line_total_grosze, part_quote_snapshot, created_at FROM order_items WHERE order_id = $1 ORDER BY created_at
`

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.FileID,
			&i.FileName,
			&i.Hash,
			&i.Process,
			&i.Quantity,
			&i.LeadTime,
			&i.UnitPriceGrosze,
			&i.LineTotalGrosze,
			&i.PartQuoteSnapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (
    short_id, quote_id, user_id, email, status, gross_total_grosze, vat_grosze,
    pricing_config_id, pricing_snapshot, locale, country, company_name, nip,
    invoice_requested, shipping_address, billing_address, status_token
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, short_id
`

type InsertOrderParams struct {
	ShortID          string
	QuoteID          uuid.UUID
	UserID           *uuid.UUID
	Email            string
	Status           string
	GrossTotalGrosze int32
	VatGrosze        int32
	PricingConfigID  uuid.UUID
	PricingSnapshot  []byte
	Locale           string
	Country          string
	CompanyName      *string
	Nip              *string
	InvoiceRequested bool
	ShippingAddress  []byte
	BillingAddress   []byte
	StatusToken      string
}

type InsertOrderRow struct {
	ID      uuid.UUID
	ShortID string
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (InsertOrderRow, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.ShortID,
		arg.QuoteID,
		arg.UserID,
		arg.Email,
		arg.Status,
		arg.GrossTotalGrosze,
		arg.VatGrosze,
		arg.PricingConfigID,
		arg.PricingSnapshot,
		arg.Locale,
		arg.Country,
		arg.CompanyName,
		arg.Nip,
		arg.InvoiceRequested,
		arg.ShippingAddress,
		arg.BillingAddress,
		arg.StatusToken,
	)
	var i InsertOrderRow
	err := row.Scan(&i.ID, &i.ShortID)
	return i, err
}

const insertOrderItem = `-- name: InsertOrderItem :exec
INSERT INTO order_items (
    order_id, file_id, file_name, hash, process, quantity, lead_time,
    unit_price_grosze, line_total_grosze, part_quote_snapshot
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type InsertOrderItemParams struct {
	OrderID           uuid.UUID
	FileID            *uuid.UUID
	FileName          string
	Hash              string
	Process           string
	Quantity          int32
	LeadTime          string
	UnitPriceGrosze   int32
	LineTotalGrosze   int32
	PartQuoteSnapshot []byte
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem,
		arg.OrderID,
		arg.FileID,
		arg.FileName,
		arg.Hash,
		arg.Process,
		arg.Quantity,
		arg.LeadTime,
		arg.UnitPriceGrosze,
		arg.LineTotalGrosze,
		arg.PartQuoteSnapshot,
	)
	return err
}

const insertPaymentEvent = `-- name: InsertPaymentEvent :execrows
INSERT INTO payments (
    order_id, provider, provider_event_id, payment_ref, type, amount_grosze, status, raw
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (provider_event_id) DO NOTHING
`

type InsertPaymentEventParams struct {
	OrderID         uuid.UUID
	Provider        string
	ProviderEventID string
	PaymentRef      *string
	Type            string
	AmountGrosze    int32
	Status          string
	Raw             []byte
}

// Idempotency spine: a redelivered provider event conflicts and inserts 0 rows,
// which the pipeline treats as an already-processed no-op.
func (q *Queries) InsertPaymentEvent(ctx context.Context, arg InsertPaymentEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPaymentEvent,
		arg.OrderID,
		arg.Provider,
		arg.ProviderEventID,
		arg.PaymentRef,
		arg.Type,
		arg.AmountGrosze,
		arg.Status,
		arg.Raw,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listInvoiceableOrders = `-- name: ListInvoiceableOrders :many
SELECT o.id, o.short_id, o.quote_id, o.user_id, o.email, o.status, o.gross_total_grosze, o.vat_grosze, o.pricing_config_id, o.created_at, o.updated_at, o.pricing_snapshot, o.locale, o.country, o.company_name, o.nip, o.invoice_requested, o.shipping_address, o.billing_address, o.status_token, o.checkout_session_id, o.checkout_session_url, o.checkout_session_expires_at, o.payment_ref, o.retention_until, o.paid_at FROM orders o
WHERE o.status = 'paid'
  AND (o.nip IS NOT NULL OR o.invoice_requested)
  AND NOT EXISTS (
      SELECT 1 FROM invoices i WHERE i.order_id = o.id AND i.kind = 'vat'
  )
ORDER BY o.paid_at
`

// Retry seam (api retry-invoices): paid orders the policy says must be invoiced
// (B2B always, B2C on request) with no VAT invoice row yet. No-op until plan 18.
func (q *Queries) ListInvoiceableOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listInvoiceableOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.ShortID,
			&i.QuoteID,
			&i.UserID,
			&i.Email,
			&i.Status,
			&i.GrossTotalGrosze,
			&i.VatGrosze,
			&i.PricingConfigID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PricingSnapshot,
			&i.Locale,
			&i.Country,
			&i.CompanyName,
			&i.Nip,
			&i.InvoiceRequested,
			&i.ShippingAddress,
			&i.BillingAddress,
			&i.StatusToken,
			&i.CheckoutSessionID,
			&i.CheckoutSessionUrl,
			&i.CheckoutSessionExpiresAt,
			&i.PaymentRef,
			&i.RetentionUntil,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByEmailOrUser = `-- name: ListOrdersByEmailOrUser :many
SELECT o.short_id, o.status, o.gross_total_grosze, o.created_at,
       (SELECT count(*) FROM order_items i WHERE i.order_id = o.id)::int AS part_count,
       (SELECT i.file_name FROM order_items i WHERE i.order_id = o.id
        ORDER BY i.created_at, i.id LIMIT 1) AS first_file_name,
       (SELECT i.lead_time FROM order_items i WHERE i.order_id = o.id
        ORDER BY i.created_at, i.id LIMIT 1) AS first_lead_time
FROM orders o
WHERE ($1::uuid IS NOT NULL AND o.user_id = $1) OR o.email = $2
ORDER BY o.created_at DESC
LIMIT 50
`

type ListOrdersByEmailOrUserParams struct {
	Column1 uuid.UUID
	Email   string
}

type ListOrdersByEmailOrUserRow struct {
	ShortID          string
	Status           string
	GrossTotalGrosze int32
	CreatedAt        pgtype.Timestamptz
	PartCount        int32
	FirstFileName    string
	FirstLeadTime    string
}

// Order history for the account page: orders placed under the session's user
// id or (for guest checkouts) its email. Newest first; part_count/first_*
// summarize the line items like ListQuotesByEmail did.
func (q *Queries) ListOrdersByEmailOrUser(ctx context.Context, arg ListOrdersByEmailOrUserParams) ([]ListOrdersByEmailOrUserRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByEmailOrUser, arg.Column1, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByEmailOrUserRow
	for rows.Next() {
		var i ListOrdersByEmailOrUserRow
		if err := rows.Scan(
			&i.ShortID,
			&i.Status,
			&i.GrossTotalGrosze,
			&i.CreatedAt,
			&i.PartCount,
			&i.FirstFileName,
			&i.FirstLeadTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderPaid = `-- name: MarkOrderPaid :execrows
UPDATE orders SET status = 'paid', paid_at = now(), payment_ref = $2, updated_at = now()
WHERE id = $1 AND status = 'draft'
`

type MarkOrderPaidParams struct {
	ID         uuid.UUID
	PaymentRef *string
}

// Transition guarded in SQL so a racing duplicate event can never double-apply;
// 0 rows means the order was not in draft (already processed or wrong state).
func (q *Queries) MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOrderPaid, arg.ID, arg.PaymentRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOrderRefunded = `-- name: MarkOrderRefunded :execrows
UPDATE orders SET status = 'refunded', updated_at = now()
WHERE id = $1 AND status = 'paid'
`

func (q *Queries) MarkOrderRefunded(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markOrderRefunded, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markQuoteOrdered = `-- name: MarkQuoteOrdered :exec
UPDATE quotes SET status = 'ordered', updated_at = now() WHERE id = $1
`

func (q *Queries) MarkQuoteOrdered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markQuoteOrdered, id)
	return err
}

const setOrderCheckoutSession = `-- name: SetOrderCheckoutSession :exec
UPDATE orders
SET checkout_session_id = $2,
    checkout_session_url = $3,
    checkout_session_expires_at = $4,
    updated_at = now()
WHERE id = $1
`

type SetOrderCheckoutSessionParams struct {
	ID                       uuid.UUID
	CheckoutSessionID        *string
	CheckoutSessionUrl       *string
	CheckoutSessionExpiresAt pgtype.Timestamptz
}

func (q *Queries) SetOrderCheckoutSession(ctx context.Context, arg SetOrderCheckoutSessionParams) error {
	_, err := q.db.Exec(ctx, setOrderCheckoutSession,
		arg.ID,
		arg.CheckoutSessionID,
		arg.CheckoutSessionUrl,
		arg.CheckoutSessionExpiresAt,
	)
	return err
}
