// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pricing_config.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deactivatePricingConfigs = `-- name: DeactivatePricingConfigs :exec
UPDATE pricing_config_snapshots SET is_active = false WHERE is_active
`

func (q *Queries) DeactivatePricingConfigs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivatePricingConfigs)
	return err
}

const getActivePricingConfig = `-- name: GetActivePricingConfig :one
SELECT id, label, config, created_at
FROM pricing_config_snapshots
WHERE is_active
LIMIT 1
`

type GetActivePricingConfigRow struct {
	ID        uuid.UUID
	Label     string
	Config    []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetActivePricingConfig(ctx context.Context) (GetActivePricingConfigRow, error) {
	row := q.db.QueryRow(ctx, getActivePricingConfig)
	var i GetActivePricingConfigRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Config,
		&i.CreatedAt,
	)
	return i, err
}

const getPricingConfigSnapshotByID = `-- name: GetPricingConfigSnapshotByID :one
SELECT id, label, config, is_active, created_at
FROM pricing_config_snapshots
WHERE id = $1
`

func (q *Queries) GetPricingConfigSnapshotByID(ctx context.Context, id uuid.UUID) (PricingConfigSnapshot, error) {
	row := q.db.QueryRow(ctx, getPricingConfigSnapshotByID, id)
	var i PricingConfigSnapshot
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const insertPricingConfigSnapshot = `-- name: InsertPricingConfigSnapshot :one
INSERT INTO pricing_config_snapshots (label, config, is_active)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertPricingConfigSnapshotParams struct {
	Label    string
	Config   []byte
	IsActive bool
}

func (q *Queries) InsertPricingConfigSnapshot(ctx context.Context, arg InsertPricingConfigSnapshotParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPricingConfigSnapshot, arg.Label, arg.Config, arg.IsActive)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listPricingConfigSnapshots = `-- name: ListPricingConfigSnapshots :many
SELECT id, label, is_active, created_at
FROM pricing_config_snapshots
ORDER BY created_at DESC
LIMIT 100
`

type ListPricingConfigSnapshotsRow struct {
	ID        uuid.UUID
	Label     string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

// Version history for the admin editor, newest first (bounded — one row per
// published edit).
func (q *Queries) ListPricingConfigSnapshots(ctx context.Context) ([]ListPricingConfigSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listPricingConfigSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPricingConfigSnapshotsRow
	for rows.Next() {
		var i ListPricingConfigSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
