// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: quotes.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getQuoteByShortID = `-- name: GetQuoteByShortID :one
SELECT id, short_id, user_id, email, country, status, prices_ex_vat, pricing_config_id, parts_subtotal_grosze, min_order_topup_grosze, order_fee_grosze, shipping_grosze, net_total_grosze, vat_grosze, gross_total_grosze, free_shipping, min_order_applied, expires_at, created_at, updated_at FROM quotes WHERE short_id = $1
`

func (q *Queries) GetQuoteByShortID(ctx context.Context, shortID string) (Quote, error) {
	row := q.db.QueryRow(ctx, getQuoteByShortID, shortID)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.UserID,
		&i.Email,
		&i.Country,
		&i.Status,
		&i.PricesExVat,
		&i.PricingConfigID,
		&i.PartsSubtotalGrosze,
		&i.MinOrderTopupGrosze,
		&i.OrderFeeGrosze,
		&i.ShippingGrosze,
		&i.NetTotalGrosze,
		&i.VatGrosze,
		&i.GrossTotalGrosze,
		&i.FreeShipping,
		&i.MinOrderApplied,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuotePartsByQuoteID = `-- name: GetQuotePartsByQuoteID :many
SELECT id, quote_id, file_id, file_name, hash, process, quantity, lead_time, unit_price_grosze, line_total_grosze, billable_volume_cm3, piece_count, plates, breakdown, dfm_flags, created_at FROM quote_parts WHERE quote_id = $1 ORDER BY created_at
`

func (q *Queries) GetQuotePartsByQuoteID(ctx context.Context, quoteID uuid.UUID) ([]QuotePart, error) {
	rows, err := q.db.Query(ctx, getQuotePartsByQuoteID, quoteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotePart
	for rows.Next() {
		var i QuotePart
		if err := rows.Scan(
			&i.ID,
			&i.QuoteID,
			&i.FileID,
			&i.FileName,
			&i.Hash,
			&i.Process,
			&i.Quantity,
			&i.LeadTime,
			&i.UnitPriceGrosze,
			&i.LineTotalGrosze,
			&i.BillableVolumeCm3,
			&i.PieceCount,
			&i.Plates,
			&i.Breakdown,
			&i.DfmFlags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertQuote = `-- name: InsertQuote :one
INSERT INTO quotes (
    short_id, user_id, email, country, prices_ex_vat, pricing_config_id,
    parts_subtotal_grosze, min_order_topup_grosze, order_fee_grosze,
    shipping_grosze, net_total_grosze, vat_grosze, gross_total_grosze,
    free_shipping, min_order_applied
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, short_id
`

type InsertQuoteParams struct {
	ShortID             string
	UserID              *uuid.UUID
	Email               *string
	Country             *string
	PricesExVat         bool
	PricingConfigID     uuid.UUID
	PartsSubtotalGrosze int32
	MinOrderTopupGrosze int32
	OrderFeeGrosze      int32
	ShippingGrosze      int32
	NetTotalGrosze      int32
	VatGrosze           int32
	GrossTotalGrosze    int32
	FreeShipping        bool
	MinOrderApplied     bool
}

type InsertQuoteRow struct {
	ID      uuid.UUID
	ShortID string
}

func (q *Queries) InsertQuote(ctx context.Context, arg InsertQuoteParams) (InsertQuoteRow, error) {
	row := q.db.QueryRow(ctx, insertQuote,
		arg.ShortID,
		arg.UserID,
		arg.Email,
		arg.Country,
		arg.PricesExVat,
		arg.PricingConfigID,
		arg.PartsSubtotalGrosze,
		arg.MinOrderTopupGrosze,
		arg.OrderFeeGrosze,
		arg.ShippingGrosze,
		arg.NetTotalGrosze,
		arg.VatGrosze,
		arg.GrossTotalGrosze,
		arg.FreeShipping,
		arg.MinOrderApplied,
	)
	var i InsertQuoteRow
	err := row.Scan(&i.ID, &i.ShortID)
	return i, err
}

const insertQuotePart = `-- name: InsertQuotePart :exec
INSERT INTO quote_parts (
    quote_id, file_id, file_name, hash, process, quantity, lead_time,
    unit_price_grosze, line_total_grosze, billable_volume_cm3,
    piece_count, plates, breakdown, dfm_flags
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type InsertQuotePartParams struct {
	QuoteID           uuid.UUID
	FileID            *uuid.UUID
	FileName          string
	Hash              string
	Process           string
	Quantity          int32
	LeadTime          string
	UnitPriceGrosze   int32
	LineTotalGrosze   int32
	BillableVolumeCm3 *float64
	PieceCount        *int32
	Plates            *int32
	Breakdown         []byte
	DfmFlags          []byte
}

func (q *Queries) InsertQuotePart(ctx context.Context, arg InsertQuotePartParams) error {
	_, err := q.db.Exec(ctx, insertQuotePart,
		arg.QuoteID,
		arg.FileID,
		arg.FileName,
		arg.Hash,
		arg.Process,
		arg.Quantity,
		arg.LeadTime,
		arg.UnitPriceGrosze,
		arg.LineTotalGrosze,
		arg.BillableVolumeCm3,
		arg.PieceCount,
		arg.Plates,
		arg.Breakdown,
		arg.DfmFlags,
	)
	return err
}

const listQuotesByEmail = `-- name: ListQuotesByEmail :many
SELECT q.short_id, q.status, q.gross_total_grosze, q.created_at,
       (SELECT count(*) FROM quote_parts p WHERE p.quote_id = q.id)::int AS part_count,
       (SELECT p.file_name FROM quote_parts p WHERE p.quote_id = q.id
        ORDER BY p.created_at, p.id LIMIT 1) AS first_file_name,
       (SELECT p.lead_time FROM quote_parts p WHERE p.quote_id = q.id
        ORDER BY p.created_at, p.id LIMIT 1) AS first_lead_time
FROM quotes q
WHERE q.email = $1
ORDER BY q.created_at DESC
LIMIT 50
`

type ListQuotesByEmailRow struct {
	ShortID          string
	Status           string
	GrossTotalGrosze int32
	CreatedAt        pgtype.Timestamptz
	PartCount        int32
	FirstFileName    string
	FirstLeadTime    string
}

// Order history for the prototype /orders page: every persisted quote is an
// order request. Newest first; part_count/first_* summarize the line items.
func (q *Queries) ListQuotesByEmail(ctx context.Context, email *string) ([]ListQuotesByEmailRow, error) {
	rows, err := q.db.Query(ctx, listQuotesByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuotesByEmailRow
	for rows.Next() {
		var i ListQuotesByEmailRow
		if err := rows.Scan(
			&i.ShortID,
			&i.Status,
			&i.GrossTotalGrosze,
			&i.CreatedAt,
			&i.PartCount,
			&i.FirstFileName,
			&i.FirstLeadTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
