// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: step_requests.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getStepRequestByShortID = `-- name: GetStepRequestByShortID :one
SELECT id, short_id, email, file_name, file_size_bytes, file_id, status, created_at FROM step_requests WHERE short_id = $1
`

func (q *Queries) GetStepRequestByShortID(ctx context.Context, shortID string) (StepRequest, error) {
	row := q.db.QueryRow(ctx, getStepRequestByShortID, shortID)
	var i StepRequest
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.Email,
		&i.FileName,
		&i.FileSizeBytes,
		&i.FileID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertStepRequest = `-- name: InsertStepRequest :one
INSERT INTO step_requests (short_id, email, file_name, file_size_bytes, file_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, short_id
`

type InsertStepRequestParams struct {
	ShortID       string
	Email         string
	FileName      string
	FileSizeBytes int64
	FileID        *uuid.UUID
}

type InsertStepRequestRow struct {
	ID      uuid.UUID
	ShortID string
}

func (q *Queries) InsertStepRequest(ctx context.Context, arg InsertStepRequestParams) (InsertStepRequestRow, error) {
	row := q.db.QueryRow(ctx, insertStepRequest,
		arg.ShortID,
		arg.Email,
		arg.FileName,
		arg.FileSizeBytes,
		arg.FileID,
	)
	var i InsertStepRequestRow
	err := row.Scan(&i.ID, &i.ShortID)
	return i, err
}

const listStepRequests = `-- name: ListStepRequests :many
SELECT id, short_id, email, file_name, file_size_bytes, file_id, status, created_at FROM step_requests
WHERE ($1::text IS NULL OR status = $1::text)
ORDER BY created_at DESC
LIMIT 200
`

// STEP manual-quote queue (plan 07), newest first, optionally by status.
func (q *Queries) ListStepRequests(ctx context.Context, status *string) ([]StepRequest, error) {
	rows, err := q.db.Query(ctx, listStepRequests, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StepRequest
	for rows.Next() {
		var i StepRequest
		if err := rows.Scan(
			&i.ID,
			&i.ShortID,
			&i.Email,
			&i.FileName,
			&i.FileSizeBytes,
			&i.FileID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStepRequestStatus = `-- name: UpdateStepRequestStatus :execrows
UPDATE step_requests SET status = $2
WHERE short_id = $1 AND status <> 'closed'
`

type UpdateStepRequestStatusParams struct {
	ShortID string
	Status  string
}

// Closed is terminal: the guard makes any transition out of 'closed' a 0-row
// no-op, which the handler maps to 409 step_request_wrong_state.
func (q *Queries) UpdateStepRequestStatus(ctx context.Context, arg UpdateStepRequestStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStepRequestStatus, arg.ShortID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
