// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: step_requests.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getStepRequestByShortID = `-- name: GetStepRequestByShortID :one
SELECT id, short_id, email, file_name, file_size_bytes, file_id, status, created_at FROM step_requests WHERE short_id = $1
`

func (q *Queries) GetStepRequestByShortID(ctx context.Context, shortID string) (StepRequest, error) {
	row := q.db.QueryRow(ctx, getStepRequestByShortID, shortID)
	var i StepRequest
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.Email,
		&i.FileName,
		&i.FileSizeBytes,
		&i.FileID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertStepRequest = `-- name: InsertStepRequest :one
INSERT INTO step_requests (short_id, email, file_name, file_size_bytes, file_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, short_id
`

type InsertStepRequestParams struct {
	ShortID       string
	Email         string
	FileName      string
	FileSizeBytes int64
	FileID        *uuid.UUID
}

type InsertStepRequestRow struct {
	ID      uuid.UUID
	ShortID string
}

func (q *Queries) InsertStepRequest(ctx context.Context, arg InsertStepRequestParams) (InsertStepRequestRow, error) {
	row := q.db.QueryRow(ctx, insertStepRequest,
		arg.ShortID,
		arg.Email,
		arg.FileName,
		arg.FileSizeBytes,
		arg.FileID,
	)
	var i InsertStepRequestRow
	err := row.Scan(&i.ID, &i.ShortID)
	return i, err
}
