// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package httpapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApiErrorCode.
const (
	FileMissingHash     ApiErrorCode = "file_missing_hash"
	FileNotFound        ApiErrorCode = "file_not_found"
	FileSizeRange       ApiErrorCode = "file_size_range"
	Internal            ApiErrorCode = "internal"
	InvalidBody         ApiErrorCode = "invalid_body"
	InvalidDesignId     ApiErrorCode = "invalid_design_id"
	InvalidEmail        ApiErrorCode = "invalid_email"
	InvalidFileSize     ApiErrorCode = "invalid_file_size"
	InvalidHash         ApiErrorCode = "invalid_hash"
	InvalidMetrics      ApiErrorCode = "invalid_metrics"
	InvalidProfileId    ApiErrorCode = "invalid_profile_id"
	MissingFileFields   ApiErrorCode = "missing_file_fields"
	MissingFileName     ApiErrorCode = "missing_file_name"
	PartsCount          ApiErrorCode = "parts_count"
	QuantityRange       ApiErrorCode = "quantity_range"
	QuoteFileInvalid    ApiErrorCode = "quote_file_invalid"
	QuoteNotFound       ApiErrorCode = "quote_not_found"
	StorageUnavailable  ApiErrorCode = "storage_unavailable"
	UnknownLeadTime     ApiErrorCode = "unknown_lead_time"
	UnknownProcess      ApiErrorCode = "unknown_process"
	UnsupportedCountry  ApiErrorCode = "unsupported_country"
	UnsupportedKind     ApiErrorCode = "unsupported_kind"
	UploadObjectMissing ApiErrorCode = "upload_object_missing"
	UploadSizeMismatch  ApiErrorCode = "upload_size_mismatch"
)

// Defines values for BreakdownLineKey.
const (
	Finishing BreakdownLineKey = "finishing"
	Machine   BreakdownLineKey = "machine"
	Material  BreakdownLineKey = "material"
	Plates    BreakdownLineKey = "plates"
)

// Defines values for CreateFileRequestKind.
const (
	N3mf CreateFileRequestKind = "3mf"
	Obj  CreateFileRequestKind = "obj"
	Step CreateFileRequestKind = "step"
	Stl  CreateFileRequestKind = "stl"
)

// Defines values for DfmFlagCode.
const (
	ExceedsBuildVolume   DfmFlagCode = "exceeds_build_volume"
	GeometryApproximated DfmFlagCode = "geometry_approximated"
	MinVolumeBilled      DfmFlagCode = "min_volume_billed"
	MultiPlate           DfmFlagCode = "multi_plate"
	SmallFeature         DfmFlagCode = "small_feature"
)

// Defines values for DfmFlagSeverity.
const (
	Block DfmFlagSeverity = "block"
	Info  DfmFlagSeverity = "info"
	Warn  DfmFlagSeverity = "warn"
)

// Defines values for EuCountry.
const (
	AT EuCountry = "AT"
	BE EuCountry = "BE"
	BG EuCountry = "BG"
	CZ EuCountry = "CZ"
	DE EuCountry = "DE"
	DK EuCountry = "DK"
	EE EuCountry = "EE"
	ES EuCountry = "ES"
	FI EuCountry = "FI"
	FR EuCountry = "FR"
	GR EuCountry = "GR"
	HR EuCountry = "HR"
	HU EuCountry = "HU"
	IE EuCountry = "IE"
	IT EuCountry = "IT"
	LT EuCountry = "LT"
	LU EuCountry = "LU"
	LV EuCountry = "LV"
	NL EuCountry = "NL"
	PL EuCountry = "PL"
	PT EuCountry = "PT"
	RO EuCountry = "RO"
	SE EuCountry = "SE"
	SI EuCountry = "SI"
	SK EuCountry = "SK"
)

// Defines values for LeadTimeId.
const (
	Economy  LeadTimeId = "economy"
	Express  LeadTimeId = "express"
	Standard LeadTimeId = "standard"
)

// Defines values for MakerworldErrorCode.
const (
	AuthExpired    MakerworldErrorCode = "auth_expired"
	DesignNotFound MakerworldErrorCode = "design_not_found"
	DownloadFailed MakerworldErrorCode = "download_failed"
	NoInstance     MakerworldErrorCode = "no_instance"
	TokenMissing   MakerworldErrorCode = "token_missing"
	TooLarge       MakerworldErrorCode = "too_large"
)

// Defines values for OrderSummaryStatus.
const (
	Expired   OrderSummaryStatus = "expired"
	Ordered   OrderSummaryStatus = "ordered"
	Submitted OrderSummaryStatus = "submitted"
)

// Defines values for ProcessId.
const (
	Asa     ProcessId = "asa"
	Iglidur ProcessId = "iglidur"
	Pa12Cf  ProcessId = "pa12_cf"
	Pctg    ProcessId = "pctg"
	Petg    ProcessId = "petg"
	PetgFr  ProcessId = "petg_fr"
	Pla     ProcessId = "pla"
)

// Defines values for SubmitQuoteRequestLocale.
const (
	En SubmitQuoteRequestLocale = "en"
	Pl SubmitQuoteRequestLocale = "pl"
)

// ApiError defines model for ApiError.
type ApiError struct {
	// Code Machine code the frontend dictionary maps to localized copy.
	Code ApiErrorCode `json:"code"`

	// Error English debug prose; never displayed to users.
	Error string `json:"error"`

	// Params Structured values for localized rendering, e.g. {"max": 5}.
	Params *map[string]interface{} `json:"params,omitempty"`
}

// ApiErrorCode Machine code the frontend dictionary maps to localized copy.
type ApiErrorCode string

// BreakdownLine defines model for BreakdownLine.
type BreakdownLine struct {
	AmountPln float64 `json:"amountPln"`

	// Count Extra-plate count; only set for key=plates.
	Count *int             `json:"count,omitempty"`
	Key   BreakdownLineKey `json:"key"`

	// Label English debug prose; the frontend renders from key (+count).
	Label *string `json:"label,omitempty"`
}

// BreakdownLineKey defines model for BreakdownLine.Key.
type BreakdownLineKey string

// CalDate defines model for CalDate.
type CalDate struct {
	D int `json:"d"`

	// M 1-12
	M int `json:"m"`
	Y int `json:"y"`
}

// CatalogLeadTime defines model for CatalogLeadTime.
type CatalogLeadTime struct {
	BusinessDays int        `json:"businessDays"`
	Id           LeadTimeId `json:"id"`
	Mult         float64    `json:"mult"`
}

// CatalogProcess defines model for CatalogProcess.
type CatalogProcess struct {
	Build       Vec3Mm    `json:"build"`
	DensityGCm3 float64   `json:"densityGCm3"`
	Factor      float64   `json:"factor"`
	Id          ProcessId `json:"id"`
	Label       string    `json:"label"`
	PlnPerHour  float64   `json:"plnPerHour"`
	PlnPerKg    float64   `json:"plnPerKg"`
}

// CatalogResponse defines model for CatalogResponse.
type CatalogResponse struct {
	DiscountTiers            []DiscountTier    `json:"discountTiers"`
	ExtraPlateFeePln         float64           `json:"extraPlateFeePln"`
	Fdm                      FdmModel          `json:"fdm"`
	FreeShippingThresholdPln float64           `json:"freeShippingThresholdPln"`
	LeadTimes                []CatalogLeadTime `json:"leadTimes"`
	MaxParts                 int               `json:"maxParts"`
	MinOrderPln              float64           `json:"minOrderPln"`
	MinPartPricePln          float64           `json:"minPartPricePln"`
	OrderFeePln              float64           `json:"orderFeePln"`
	Processes                []CatalogProcess  `json:"processes"`
	QuantityChips            []int             `json:"quantityChips"`
	ShippingFlatPln          float64           `json:"shippingFlatPln"`
	VatRate                  float64           `json:"vatRate"`
}

// ConfirmFileResponse defines model for ConfirmFileResponse.
type ConfirmFileResponse struct {
	FileId openapi_types.UUID `json:"fileId"`
	Stored bool               `json:"stored"`
}

// CreateFileRequest defines model for CreateFileRequest.
type CreateFileRequest struct {
	FileName  string                `json:"fileName"`
	Kind      CreateFileRequestKind `json:"kind"`
	Sha256    string                `json:"sha256"`
	SizeBytes int64                 `json:"sizeBytes"`
}

// CreateFileRequestKind defines model for CreateFileRequest.Kind.
type CreateFileRequestKind string

// CreateFileResponse defines model for CreateFileResponse.
type CreateFileResponse struct {
	AlreadyStored bool               `json:"alreadyStored"`
	FileId        openapi_types.UUID `json:"fileId"`

	// UploadUrl Presigned PUT URL; absent when alreadyStored is true
	UploadUrl *string `json:"uploadUrl,omitempty"`
}

// DfmFlag defines model for DfmFlag.
type DfmFlag struct {
	Code DfmFlagCode `json:"code"`

	// Message English debug prose; the frontend renders from code+params.
	Message *string `json:"message,omitempty"`

	// Params Structured values for localized rendering, e.g. {"x": 340}.
	Params             *map[string]interface{} `json:"params,omitempty"`
	Severity           DfmFlagSeverity         `json:"severity"`
	SuggestedProcesses *[]ProcessId            `json:"suggestedProcesses,omitempty"`
}

// DfmFlagCode defines model for DfmFlag.Code.
type DfmFlagCode string

// DfmFlagSeverity defines model for DfmFlag.Severity.
type DfmFlagSeverity string

// DiscountTier defines model for DiscountTier.
type DiscountTier struct {
	Fraction float64 `json:"fraction"`
	Quantity int     `json:"quantity"`
}

// EuCountry Supported EU shipping destinations
type EuCountry string

// FdmModel defines model for FdmModel.
type FdmModel struct {
	InfillFraction          float64 `json:"infillFraction"`
	InfillGramsPerPrintHour float64 `json:"infillGramsPerPrintHour"`
	ShellGramsPerPrintHour  float64 `json:"shellGramsPerPrintHour"`
	ShellThicknessMm        float64 `json:"shellThicknessMm"`
}

// LeadTimeId defines model for LeadTimeId.
type LeadTimeId string

// ListOrdersResponse defines model for ListOrdersResponse.
type ListOrdersResponse struct {
	Orders []OrderSummary `json:"orders"`
}

// MakerworldError defines model for MakerworldError.
type MakerworldError struct {
	Code MakerworldErrorCode `json:"code"`
}

// MakerworldErrorCode defines model for MakerworldError.Code.
type MakerworldErrorCode string

// MakerworldFetchRequest defines model for MakerworldFetchRequest.
type MakerworldFetchRequest struct {
	DesignId  int64  `json:"designId"`
	ProfileId *int64 `json:"profileId,omitempty"`
}

// MeshMetrics Pricing-relevant subset of client-side mesh analysis
type MeshMetrics struct {
	BboxMm Vec3Mm `json:"bboxMm"`

	// Pieces Per-piece bounding boxes for multi-item 3MF files
	Pieces           *[]PieceMetrics `json:"pieces,omitempty"`
	SurfaceAreaCm2   float64         `json:"surfaceAreaCm2"`
	UsedHullFallback bool            `json:"usedHullFallback"`
	VolumeCm3        float64         `json:"volumeCm3"`
}

// OrderSummary defines model for OrderSummary.
type OrderSummary struct {
	CreatedAt time.Time `json:"createdAt"`

	// FileName First part's file name
	FileName      string     `json:"fileName"`
	GrossTotalPln float64    `json:"grossTotalPln"`
	LeadTime      LeadTimeId `json:"leadTime"`
	PartCount     int        `json:"partCount"`

	// QuoteId e.g. "Q-1A2B3C4D"
	QuoteId string             `json:"quoteId"`
	Status  OrderSummaryStatus `json:"status"`
}

// OrderSummaryStatus defines model for OrderSummary.Status.
type OrderSummaryStatus string

// OrderTotals defines model for OrderTotals.
type OrderTotals struct {
	FreeShipping     bool    `json:"freeShipping"`
	GrossTotalPln    float64 `json:"grossTotalPln"`
	MinOrderApplied  bool    `json:"minOrderApplied"`
	MinOrderTopUpPln float64 `json:"minOrderTopUpPln"`
	NetTotalPln      float64 `json:"netTotalPln"`
	OrderFeePln      float64 `json:"orderFeePln"`
	PartsSubtotalPln float64 `json:"partsSubtotalPln"`
	ShippingPln      float64 `json:"shippingPln"`
	VatPln           float64 `json:"vatPln"`
}

// PartQuote defines model for PartQuote.
type PartQuote struct {
	BillableVolumeCm3  float64         `json:"billableVolumeCm3"`
	Blocked            bool            `json:"blocked"`
	Breakdown          []BreakdownLine `json:"breakdown"`
	DfmFlags           []DfmFlag       `json:"dfmFlags"`
	DiscountFraction   float64         `json:"discountFraction"`
	LeadTimeMultiplier float64         `json:"leadTimeMultiplier"`
	LineTotalPln       float64         `json:"lineTotalPln"`

	// PieceCount Present only for multi-piece 3MF parts
	PieceCount *int `json:"pieceCount,omitempty"`

	// Plates Present only for multi-piece 3MF parts
	Plates      *int         `json:"plates,omitempty"`
	PriceBreaks []PriceBreak `json:"priceBreaks"`

	// PrintHours Estimated print time in hours
	PrintHours   float64 `json:"printHours"`
	UnitBasePln  float64 `json:"unitBasePln"`
	UnitPricePln float64 `json:"unitPricePln"`

	// WeightG Estimated print weight (shell + infill model)
	WeightG float64 `json:"weightG"`
}

// PieceMetrics defines model for PieceMetrics.
type PieceMetrics struct {
	BboxMm Vec3Mm `json:"bboxMm"`
}

// PriceBreak defines model for PriceBreak.
type PriceBreak struct {
	DiscountFraction float64 `json:"discountFraction"`
	Quantity         int     `json:"quantity"`
	UnitPricePln     float64 `json:"unitPricePln"`
}

// PricePart defines model for PricePart.
type PricePart struct {
	LeadTime LeadTimeId `json:"leadTime"`

	// Metrics Pricing-relevant subset of client-side mesh analysis
	Metrics  MeshMetrics `json:"metrics"`
	Process  ProcessId   `json:"process"`
	Quantity int         `json:"quantity"`
}

// PriceRequest defines model for PriceRequest.
type PriceRequest struct {
	Parts []PricePart `json:"parts"`
}

// PriceResponse defines model for PriceResponse.
type PriceResponse struct {
	Parts  []PartQuote `json:"parts"`
	Totals OrderTotals `json:"totals"`
}

// ProcessId defines model for ProcessId.
type ProcessId string

// ShipDate defines model for ShipDate.
type ShipDate struct {
	Date                CalDate `json:"date"`
	DispatchStartsToday bool    `json:"dispatchStartsToday"`

	// Label e.g. "Thu 16 Jul" (canonical engine label; UI formats the date per locale)
	Label    string     `json:"label"`
	LeadTime LeadTimeId `json:"leadTime"`
}

// ShipDatesResponse defines model for ShipDatesResponse.
type ShipDatesResponse struct {
	ShipDates []ShipDate `json:"shipDates"`
}

// StepQuoteRequest defines model for StepQuoteRequest.
type StepQuoteRequest struct {
	Email    openapi_types.Email `json:"email"`
	FileName string              `json:"fileName"`
	FileSize int                 `json:"fileSize"`
}

// StepQuoteResponse defines model for StepQuoteResponse.
type StepQuoteResponse struct {
	// RequestId e.g. "STEP-1A2B3C4D"
	RequestId string `json:"requestId"`
}

// SubmitQuotePart defines model for SubmitQuotePart.
type SubmitQuotePart struct {
	// FileId The stored file backing this part (plan 02). When present the server verifies it exists with a matching hash and links it.
	FileId   *openapi_types.UUID `json:"fileId,omitempty"`
	FileName string              `json:"fileName"`
	Hash     string              `json:"hash"`
	LeadTime LeadTimeId          `json:"leadTime"`

	// Metrics Pricing-relevant subset of client-side mesh analysis
	Metrics  MeshMetrics `json:"metrics"`
	Process  ProcessId   `json:"process"`
	Quantity int         `json:"quantity"`
}

// SubmitQuoteRequest defines model for SubmitQuoteRequest.
type SubmitQuoteRequest struct {
	// ClientGrossTotalPln The gross total the client displayed, for mismatch telemetry. The server's own computation is authoritative.
	ClientGrossTotalPln *float64 `json:"clientGrossTotalPln,omitempty"`

	// Country Supported EU shipping destinations
	Country EuCountry           `json:"country"`
	Email   openapi_types.Email `json:"email"`

	// Locale UI locale at submit time; persisted for downstream emails and invoices (plans 05/06 read it).
	Locale *SubmitQuoteRequestLocale `json:"locale,omitempty"`
	Parts  []SubmitQuotePart         `json:"parts"`
}

// SubmitQuoteRequestLocale UI locale at submit time; persisted for downstream emails and invoices (plans 05/06 read it).
type SubmitQuoteRequestLocale string

// SubmitQuoteResponse defines model for SubmitQuoteResponse.
type SubmitQuoteResponse struct {
	// QuoteId e.g. "Q-1A2B3C4D"
	QuoteId string      `json:"quoteId"`
	Totals  OrderTotals `json:"totals"`
}

// Vec3Mm defines model for Vec3Mm.
type Vec3Mm struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ApiError

// NotFound defines model for NotFound.
type NotFound = ApiError

// ListOrdersParams defines parameters for ListOrders.
type ListOrdersParams struct {
	Email openapi_types.Email `form:"email" json:"email"`
}

// CreateFileUploadJSONRequestBody defines body for CreateFileUpload for application/json ContentType.
type CreateFileUploadJSONRequestBody = CreateFileRequest

// FetchMakerworldModelJSONRequestBody defines body for FetchMakerworldModel for application/json ContentType.
type FetchMakerworldModelJSONRequestBody = MakerworldFetchRequest

// PriceJSONRequestBody defines body for Price for application/json ContentType.
type PriceJSONRequestBody = PriceRequest

// SubmitQuoteJSONRequestBody defines body for SubmitQuote for application/json ContentType.
type SubmitQuoteJSONRequestBody = SubmitQuoteRequest

// SubmitStepQuoteJSONRequestBody defines body for SubmitStepQuote for application/json ContentType.
type SubmitStepQuoteJSONRequestBody = StepQuoteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Pricing catalog for display (processes, lead times, fees)
	// (GET /api/v1/config)
	GetConfig(w http.ResponseWriter, r *http.Request)
	// Reserve a file record and get a presigned upload URL (dedups by hash)
	// (POST /api/v1/files)
	CreateFileUpload(w http.ResponseWriter, r *http.Request)
	// Confirm a presigned upload completed; verifies the stored object size
	// (POST /api/v1/files/{fileId}/confirm)
	ConfirmFileUpload(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID)
	// Download a MakerWorld model's 3MF via Bambu Cloud
	// (POST /api/v1/makerworld/fetch)
	FetchMakerworldModel(w http.ResponseWriter, r *http.Request)
	// List order requests (submitted quotes) for an email. Prototype access control: the login page gates this with a simulated one-time code, so treat the data as non-sensitive until plan 05 adds real auth.
	// (GET /api/v1/orders)
	ListOrders(w http.ResponseWriter, r *http.Request, params ListOrdersParams)
	// Price a set of parts and compute order totals
	// (POST /api/v1/price)
	Price(w http.ResponseWriter, r *http.Request)
	// Submit an order request; prices are recomputed server-side
	// (POST /api/v1/quotes)
	SubmitQuote(w http.ResponseWriter, r *http.Request)
	// Read back a submitted quote by its id. The id is an unguessable capability token (the quoteId returned by submitQuote); the response is pricing-only and carries no customer PII.
	// (GET /api/v1/quotes/{id})
	GetQuote(w http.ResponseWriter, r *http.Request, id string)
	// Estimated ship dates per lead time (Europe/Warsaw clock)
	// (GET /api/v1/ship-dates)
	GetShipDates(w http.ResponseWriter, r *http.Request)
	// Request a manual quote for a STEP file
	// (POST /api/v1/step-quotes)
	SubmitStepQuote(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Pricing catalog for display (processes, lead times, fees)
// (GET /api/v1/config)
func (_ Unimplemented) GetConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reserve a file record and get a presigned upload URL (dedups by hash)
// (POST /api/v1/files)
func (_ Unimplemented) CreateFileUpload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Confirm a presigned upload completed; verifies the stored object size
// (POST /api/v1/files/{fileId}/confirm)
func (_ Unimplemented) ConfirmFileUpload(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download a MakerWorld model's 3MF via Bambu Cloud
// (POST /api/v1/makerworld/fetch)
func (_ Unimplemented) FetchMakerworldModel(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List order requests (submitted quotes) for an email. Prototype access control: the login page gates this with a simulated one-time code, so treat the data as non-sensitive until plan 05 adds real auth.
// (GET /api/v1/orders)
func (_ Unimplemented) ListOrders(w http.ResponseWriter, r *http.Request, params ListOrdersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Price a set of parts and compute order totals
// (POST /api/v1/price)
func (_ Unimplemented) Price(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit an order request; prices are recomputed server-side
// (POST /api/v1/quotes)
func (_ Unimplemented) SubmitQuote(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read back a submitted quote by its id. The id is an unguessable capability token (the quoteId returned by submitQuote); the response is pricing-only and carries no customer PII.
// (GET /api/v1/quotes/{id})
func (_ Unimplemented) GetQuote(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Estimated ship dates per lead time (Europe/Warsaw clock)
// (GET /api/v1/ship-dates)
func (_ Unimplemented) GetShipDates(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request a manual quote for a STEP file
// (POST /api/v1/step-quotes)
func (_ Unimplemented) SubmitStepQuote(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetConfig operation middleware
func (siw *ServerInterfaceWrapper) GetConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateFileUpload operation middleware
func (siw *ServerInterfaceWrapper) CreateFileUpload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateFileUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmFileUpload operation middleware
func (siw *ServerInterfaceWrapper) ConfirmFileUpload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "fileId" -------------
	var fileId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "fileId", chi.URLParam(r, "fileId"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fileId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmFileUpload(w, r, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FetchMakerworldModel operation middleware
func (siw *ServerInterfaceWrapper) FetchMakerworldModel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FetchMakerworldModel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrders operation middleware
func (siw *ServerInterfaceWrapper) ListOrders(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListOrdersParams

	// ------------- Required query parameter "email" -------------

	if paramValue := r.URL.Query().Get("email"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "email"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "email", r.URL.Query(), &params.Email)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "email", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Price operation middleware
func (siw *ServerInterfaceWrapper) Price(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Price(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitQuote operation middleware
func (siw *ServerInterfaceWrapper) SubmitQuote(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitQuote(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQuote operation middleware
func (siw *ServerInterfaceWrapper) GetQuote(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQuote(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetShipDates operation middleware
func (siw *ServerInterfaceWrapper) GetShipDates(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetShipDates(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitStepQuote operation middleware
func (siw *ServerInterfaceWrapper) SubmitStepQuote(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitStepQuote(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/config", wrapper.GetConfig)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/files", wrapper.CreateFileUpload)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/files/{fileId}/confirm", wrapper.ConfirmFileUpload)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/makerworld/fetch", wrapper.FetchMakerworldModel)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/orders", wrapper.ListOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/price", wrapper.Price)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/quotes", wrapper.SubmitQuote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/quotes/{id}", wrapper.GetQuote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ship-dates", wrapper.GetShipDates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/step-quotes", wrapper.SubmitStepQuote)
	})

	return r
}
