// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package httpapi

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AdminInvoiceKind.
const (
	Correction AdminInvoiceKind = "correction"
	Proforma   AdminInvoiceKind = "proforma"
	Vat        AdminInvoiceKind = "vat"
)

// Defines values for AdminPaymentType.
const (
	Payment AdminPaymentType = "payment"
	Refund  AdminPaymentType = "refund"
)

// Defines values for AdminStepRequestSummaryStatus.
const (
	AdminStepRequestSummaryStatusClosed AdminStepRequestSummaryStatus = "closed"
	AdminStepRequestSummaryStatusNew    AdminStepRequestSummaryStatus = "new"
	AdminStepRequestSummaryStatusQuoted AdminStepRequestSummaryStatus = "quoted"
)

// Defines values for ApiErrorCode.
const (
	CodeExpired           ApiErrorCode = "code_expired"
	CodeInvalid           ApiErrorCode = "code_invalid"
	EraseNotEnabled       ApiErrorCode = "erase_not_enabled"
	FileMissingHash       ApiErrorCode = "file_missing_hash"
	FileNotFound          ApiErrorCode = "file_not_found"
	FileSizeRange         ApiErrorCode = "file_size_range"
	Internal              ApiErrorCode = "internal"
	InvalidBody           ApiErrorCode = "invalid_body"
	InvalidDesignId       ApiErrorCode = "invalid_design_id"
	InvalidEmail          ApiErrorCode = "invalid_email"
	InvalidFileSize       ApiErrorCode = "invalid_file_size"
	InvalidHash           ApiErrorCode = "invalid_hash"
	InvalidMetrics        ApiErrorCode = "invalid_metrics"
	InvalidNip            ApiErrorCode = "invalid_nip"
	InvalidProfileId      ApiErrorCode = "invalid_profile_id"
	MissingFileFields     ApiErrorCode = "missing_file_fields"
	MissingFileName       ApiErrorCode = "missing_file_name"
	OrderNotFound         ApiErrorCode = "order_not_found"
	OrderWrongState       ApiErrorCode = "order_wrong_state"
	PartsCount            ApiErrorCode = "parts_count"
	PricingConfigInvalid  ApiErrorCode = "pricing_config_invalid"
	QuantityRange         ApiErrorCode = "quantity_range"
	QuoteAlreadyOrdered   ApiErrorCode = "quote_already_ordered"
	QuoteFileInvalid      ApiErrorCode = "quote_file_invalid"
	QuoteNotFound         ApiErrorCode = "quote_not_found"
	StepRequestNotFound   ApiErrorCode = "step_request_not_found"
	StepRequestWrongState ApiErrorCode = "step_request_wrong_state"
	StorageUnavailable    ApiErrorCode = "storage_unavailable"
	TooManyAttempts       ApiErrorCode = "too_many_attempts"
	TrackingRequired      ApiErrorCode = "tracking_required"
	TransitionNotAllowed  ApiErrorCode = "transition_not_allowed"
	Unauthorized          ApiErrorCode = "unauthorized"
	UnknownLeadTime       ApiErrorCode = "unknown_lead_time"
	UnknownProcess        ApiErrorCode = "unknown_process"
	UnsupportedCountry    ApiErrorCode = "unsupported_country"
	UnsupportedKind       ApiErrorCode = "unsupported_kind"
	UploadObjectMissing   ApiErrorCode = "upload_object_missing"
	UploadSizeMismatch    ApiErrorCode = "upload_size_mismatch"
)

// Defines values for BreakdownLineKey.
const (
	Finishing BreakdownLineKey = "finishing"
	Machine   BreakdownLineKey = "machine"
	Material  BreakdownLineKey = "material"
	Plates    BreakdownLineKey = "plates"
)

// Defines values for CreateFileRequestKind.
const (
	N3mf CreateFileRequestKind = "3mf"
	Obj  CreateFileRequestKind = "obj"
	Step CreateFileRequestKind = "step"
	Stl  CreateFileRequestKind = "stl"
)

// Defines values for DfmFlagCode.
const (
	ExceedsBuildVolume   DfmFlagCode = "exceeds_build_volume"
	GeometryApproximated DfmFlagCode = "geometry_approximated"
	MinVolumeBilled      DfmFlagCode = "min_volume_billed"
	MultiPlate           DfmFlagCode = "multi_plate"
	SmallFeature         DfmFlagCode = "small_feature"
)

// Defines values for DfmFlagSeverity.
const (
	Block DfmFlagSeverity = "block"
	Info  DfmFlagSeverity = "info"
	Warn  DfmFlagSeverity = "warn"
)

// Defines values for EuCountry.
const (
	AT EuCountry = "AT"
	BE EuCountry = "BE"
	BG EuCountry = "BG"
	CZ EuCountry = "CZ"
	DE EuCountry = "DE"
	DK EuCountry = "DK"
	EE EuCountry = "EE"
	ES EuCountry = "ES"
	FI EuCountry = "FI"
	FR EuCountry = "FR"
	GR EuCountry = "GR"
	HR EuCountry = "HR"
	HU EuCountry = "HU"
	IE EuCountry = "IE"
	IT EuCountry = "IT"
	LT EuCountry = "LT"
	LU EuCountry = "LU"
	LV EuCountry = "LV"
	NL EuCountry = "NL"
	PL EuCountry = "PL"
	PT EuCountry = "PT"
	RO EuCountry = "RO"
	SE EuCountry = "SE"
	SI EuCountry = "SI"
	SK EuCountry = "SK"
)

// Defines values for LeadTimeId.
const (
	Economy  LeadTimeId = "economy"
	Express  LeadTimeId = "express"
	Standard LeadTimeId = "standard"
)

// Defines values for MakerworldErrorCode.
const (
	AuthExpired    MakerworldErrorCode = "auth_expired"
	DesignNotFound MakerworldErrorCode = "design_not_found"
	DownloadFailed MakerworldErrorCode = "download_failed"
	NoInstance     MakerworldErrorCode = "no_instance"
	TokenMissing   MakerworldErrorCode = "token_missing"
	TooLarge       MakerworldErrorCode = "too_large"
)

// Defines values for MeResponseRole.
const (
	Admin    MeResponseRole = "admin"
	Customer MeResponseRole = "customer"
)

// Defines values for OrderStatus.
const (
	Cancelled    OrderStatus = "cancelled"
	Delivered    OrderStatus = "delivered"
	Draft        OrderStatus = "draft"
	InProduction OrderStatus = "in_production"
	Paid         OrderStatus = "paid"
	Refunded     OrderStatus = "refunded"
	Shipped      OrderStatus = "shipped"
)

// Defines values for ProcessId.
const (
	Asa     ProcessId = "asa"
	Iglidur ProcessId = "iglidur"
	Pa12Cf  ProcessId = "pa12_cf"
	Pctg    ProcessId = "pctg"
	Petg    ProcessId = "petg"
	PetgFr  ProcessId = "petg_fr"
	Pla     ProcessId = "pla"
)

// Defines values for SubmitQuoteRequestLocale.
const (
	En SubmitQuoteRequestLocale = "en"
	Pl SubmitQuoteRequestLocale = "pl"
)

// Defines values for UpdateStepRequestStatusRequestStatus.
const (
	UpdateStepRequestStatusRequestStatusClosed UpdateStepRequestStatusRequestStatus = "closed"
	UpdateStepRequestStatusRequestStatusQuoted UpdateStepRequestStatusRequestStatus = "quoted"
)

// Defines values for AdminListStepRequestsParamsStatus.
const (
	Closed AdminListStepRequestsParamsStatus = "closed"
	New    AdminListStepRequestsParamsStatus = "new"
	Quoted AdminListStepRequestsParamsStatus = "quoted"
)

// Address defines model for Address.
type Address struct {
	City string `json:"city"`

	// Name Full name (B2C) or company name (B2B)
	Name       string `json:"name"`
	PostalCode string `json:"postalCode"`

	// Street Street and number
	Street string `json:"street"`
}

// AdminCustomerExport defines model for AdminCustomerExport.
type AdminCustomerExport struct {
	Email        string                    `json:"email"`
	ExportedAt   time.Time                 `json:"exportedAt"`
	Files        []AdminFileSummary        `json:"files"`
	Orders       []AdminOrderDetail        `json:"orders"`
	Quotes       []AdminQuoteSummary       `json:"quotes"`
	StepRequests []AdminStepRequestSummary `json:"stepRequests"`
	User         *AdminUserSummary         `json:"user,omitempty"`
}

// AdminCustomerLookup defines model for AdminCustomerLookup.
type AdminCustomerLookup struct {
	Email        string                    `json:"email"`
	Files        []AdminFileSummary        `json:"files"`
	Orders       []AdminOrderSummary       `json:"orders"`
	Quotes       []AdminQuoteSummary       `json:"quotes"`
	StepRequests []AdminStepRequestSummary `json:"stepRequests"`
	User         *AdminUserSummary         `json:"user,omitempty"`
}

// AdminEraseEntry defines model for AdminEraseEntry.
type AdminEraseEntry struct {
	Count int     `json:"count"`
	Note  *string `json:"note,omitempty"`
	Table string  `json:"table"`
}

// AdminEraseReport defines model for AdminEraseReport.
type AdminEraseReport struct {
	DryRun      bool                 `json:"dryRun"`
	Email       string               `json:"email"`
	Retained    []AdminEraseRetained `json:"retained"`
	WouldDelete []AdminEraseEntry    `json:"wouldDelete"`
}

// AdminEraseRetained defines model for AdminEraseRetained.
type AdminEraseRetained struct {
	Count  int    `json:"count"`
	Reason string `json:"reason"`
	Table  string `json:"table"`
}

// AdminFileSummary defines model for AdminFileSummary.
type AdminFileSummary struct {
	CreatedAt time.Time          `json:"createdAt"`
	FileId    openapi_types.UUID `json:"fileId"`
	FileName  string             `json:"fileName"`
	Kind      string             `json:"kind"`
	SizeBytes int64              `json:"sizeBytes"`

	// Stored True when the object bytes are in storage.
	Stored bool `json:"stored"`
}

// AdminInvoice defines model for AdminInvoice.
type AdminInvoice struct {
	CreatedAt  time.Time        `json:"createdAt"`
	IssuedAt   *time.Time       `json:"issuedAt,omitempty"`
	Kind       AdminInvoiceKind `json:"kind"`
	Number     *string          `json:"number,omitempty"`
	PdfUrl     *string          `json:"pdfUrl,omitempty"`
	ProviderId *string          `json:"providerId,omitempty"`

	// RetentionUntil YYYY-MM-DD; blocks GDPR erasure (plan 09).
	RetentionUntil *string `json:"retentionUntil,omitempty"`
}

// AdminInvoiceKind defines model for AdminInvoice.Kind.
type AdminInvoiceKind string

// AdminListOrdersResponse defines model for AdminListOrdersResponse.
type AdminListOrdersResponse struct {
	Limit  int                 `json:"limit"`
	Offset int                 `json:"offset"`
	Orders []AdminOrderSummary `json:"orders"`
	Total  int                 `json:"total"`
}

// AdminOpsStats defines model for AdminOpsStats.
type AdminOpsStats struct {
	ByStatus []struct {
		Count  int    `json:"count"`
		Status string `json:"status"`
	} `json:"byStatus"`

	// Daily 14 entries, oldest first, ending today; zero-filled.
	Daily []struct {
		Date     string  `json:"date"`
		GrossPln float32 `json:"grossPln"`
		Orders   int     `json:"orders"`
	} `json:"daily"`

	// Date Today in Europe/Warsaw, YYYY-MM-DD.
	Date string `json:"date"`

	// Overdue Open orders (paid/in_production) whose ship-by is past.
	Overdue           int     `json:"overdue"`
	StepNew           int     `json:"stepNew"`
	TodayGrossPln     float32 `json:"todayGrossPln"`
	TodayOrders       int     `json:"todayOrders"`
	YesterdayGrossPln float32 `json:"yesterdayGrossPln"`
	YesterdayOrders   int     `json:"yesterdayOrders"`
}

// AdminOpsToday defines model for AdminOpsToday.
type AdminOpsToday struct {
	// Date Today in Europe/Warsaw, YYYY-MM-DD.
	Date   string              `json:"date"`
	Orders []AdminOrderSummary `json:"orders"`
}

// AdminOrder defines model for AdminOrder.
type AdminOrder struct {
	BillingAddress   *Address           `json:"billingAddress,omitempty"`
	CompanyName      *string            `json:"companyName,omitempty"`
	Country          string             `json:"country"`
	CreatedAt        time.Time          `json:"createdAt"`
	Email            string             `json:"email"`
	GrossTotalPln    float64            `json:"grossTotalPln"`
	InvoiceRequested bool               `json:"invoiceRequested"`
	Locale           string             `json:"locale"`
	Nip              *string            `json:"nip,omitempty"`
	OrderId          string             `json:"orderId"`
	PaidAt           *time.Time         `json:"paidAt,omitempty"`
	PricingConfigId  openapi_types.UUID `json:"pricingConfigId"`
	ShippingAddress  Address            `json:"shippingAddress"`

	// Status Order lifecycle state; transitions are owned by the backend state machine (internal/orders).
	Status OrderStatus `json:"status"`

	// StatusToken Public status-page capability — exposed because this endpoint is admin-only (support may send the customer their tracking link).
	StatusToken    string      `json:"statusToken"`
	Totals         OrderTotals `json:"totals"`
	TrackingNumber *string     `json:"trackingNumber,omitempty"`
	VatPln         float64     `json:"vatPln"`
}

// AdminOrderDetail defines model for AdminOrderDetail.
type AdminOrderDetail struct {
	Invoices []AdminInvoice   `json:"invoices"`
	Items    []AdminOrderItem `json:"items"`
	Order    AdminOrder       `json:"order"`
	Payments []AdminPayment   `json:"payments"`
}

// AdminOrderItem defines model for AdminOrderItem.
type AdminOrderItem struct {
	FileId       *openapi_types.UUID `json:"fileId,omitempty"`
	FileName     string              `json:"fileName"`
	LeadTime     LeadTimeId          `json:"leadTime"`
	LineTotalPln float64             `json:"lineTotalPln"`

	// PartQuoteSnapshot The part's frozen PartQuote (breakdown, dfmFlags, plates) copied at order time; shape pinned by the pricing engine, not the spec.
	PartQuoteSnapshot *map[string]interface{} `json:"partQuoteSnapshot,omitempty"`
	Process           ProcessId               `json:"process"`
	Quantity          int                     `json:"quantity"`
	UnitPricePln      float64                 `json:"unitPricePln"`
}

// AdminOrderSummary defines model for AdminOrderSummary.
type AdminOrderSummary struct {
	CreatedAt time.Time `json:"createdAt"`

	// DfmCodes Distinct flag codes behind dfmFlagged.
	DfmCodes *[]string `json:"dfmCodes,omitempty"`

	// DfmFlagged Any item carries a warn/block/manual_verify DFM flag.
	DfmFlagged    bool    `json:"dfmFlagged"`
	Email         string  `json:"email"`
	GrossTotalPln float64 `json:"grossTotalPln"`
	OrderId       string  `json:"orderId"`

	// Overdue Present and true when shipBy is before today (Warsaw).
	Overdue   *bool      `json:"overdue,omitempty"`
	PaidAt    *time.Time `json:"paidAt,omitempty"`
	PartCount int        `json:"partCount"`

	// ShipBy Ship-by date (YYYY-MM-DD, Warsaw business calendar) derived from the lead-time engine; present only once the order is paid.
	ShipBy *string `json:"shipBy,omitempty"`

	// Status Order lifecycle state; transitions are owned by the backend state machine (internal/orders).
	Status         OrderStatus `json:"status"`
	TrackingNumber *string     `json:"trackingNumber,omitempty"`
}

// AdminPayment defines model for AdminPayment.
type AdminPayment struct {
	AmountPln       float64          `json:"amountPln"`
	CreatedAt       time.Time        `json:"createdAt"`
	PaymentRef      *string          `json:"paymentRef,omitempty"`
	Provider        string           `json:"provider"`
	ProviderEventId string           `json:"providerEventId"`
	Status          string           `json:"status"`
	Type            AdminPaymentType `json:"type"`
}

// AdminPaymentType defines model for AdminPayment.Type.
type AdminPaymentType string

// AdminPricingConfigResponse defines model for AdminPricingConfigResponse.
type AdminPricingConfigResponse struct {
	Active  PricingConfigSnapshot       `json:"active"`
	History []PricingConfigSnapshotMeta `json:"history"`
}

// AdminQuoteSummary defines model for AdminQuoteSummary.
type AdminQuoteSummary struct {
	CreatedAt     time.Time `json:"createdAt"`
	FileName      *string   `json:"fileName,omitempty"`
	GrossTotalPln float64   `json:"grossTotalPln"`
	PartCount     int       `json:"partCount"`
	QuoteId       string    `json:"quoteId"`
	Status        string    `json:"status"`
}

// AdminStepRequestList defines model for AdminStepRequestList.
type AdminStepRequestList struct {
	Requests []AdminStepRequestSummary `json:"requests"`
}

// AdminStepRequestSummary defines model for AdminStepRequestSummary.
type AdminStepRequestSummary struct {
	CreatedAt     time.Time                     `json:"createdAt"`
	Email         string                        `json:"email"`
	FileId        *openapi_types.UUID           `json:"fileId,omitempty"`
	FileName      string                        `json:"fileName"`
	FileSizeBytes int64                         `json:"fileSizeBytes"`
	RequestId     string                        `json:"requestId"`
	Status        AdminStepRequestSummaryStatus `json:"status"`
}

// AdminStepRequestSummaryStatus defines model for AdminStepRequestSummary.Status.
type AdminStepRequestSummaryStatus string

// AdminUserSummary defines model for AdminUserSummary.
type AdminUserSummary struct {
	CreatedAt time.Time          `json:"createdAt"`
	Email     string             `json:"email"`
	Id        openapi_types.UUID `json:"id"`
	Role      string             `json:"role"`
}

// ApiError defines model for ApiError.
type ApiError struct {
	// Code Machine code the frontend dictionary maps to localized copy.
	Code ApiErrorCode `json:"code"`

	// Error English debug prose; never displayed to users.
	Error string `json:"error"`

	// Params Structured values for localized rendering, e.g. {"max": 5}.
	Params *map[string]interface{} `json:"params,omitempty"`
}

// ApiErrorCode Machine code the frontend dictionary maps to localized copy.
type ApiErrorCode string

// BreakdownLine defines model for BreakdownLine.
type BreakdownLine struct {
	AmountPln float64 `json:"amountPln"`

	// Count Extra-plate count; only set for key=plates.
	Count *int             `json:"count,omitempty"`
	Key   BreakdownLineKey `json:"key"`

	// Label English debug prose; the frontend renders from key (+count).
	Label *string `json:"label,omitempty"`
}

// BreakdownLineKey defines model for BreakdownLine.Key.
type BreakdownLineKey string

// CalDate defines model for CalDate.
type CalDate struct {
	D int `json:"d"`

	// M 1-12
	M int `json:"m"`
	Y int `json:"y"`
}

// CatalogLeadTime defines model for CatalogLeadTime.
type CatalogLeadTime struct {
	BusinessDays int        `json:"businessDays"`
	Id           LeadTimeId `json:"id"`
	Mult         float64    `json:"mult"`
}

// CatalogProcess defines model for CatalogProcess.
type CatalogProcess struct {
	Build       Vec3Mm    `json:"build"`
	DensityGCm3 float64   `json:"densityGCm3"`
	Factor      float64   `json:"factor"`
	Id          ProcessId `json:"id"`
	Label       string    `json:"label"`
	PlnPerHour  float64   `json:"plnPerHour"`
	PlnPerKg    float64   `json:"plnPerKg"`
}

// CatalogResponse defines model for CatalogResponse.
type CatalogResponse struct {
	DiscountTiers            []DiscountTier    `json:"discountTiers"`
	ExtraPlateFeePln         float64           `json:"extraPlateFeePln"`
	Fdm                      FdmModel          `json:"fdm"`
	FreeShippingThresholdPln float64           `json:"freeShippingThresholdPln"`
	LeadTimes                []CatalogLeadTime `json:"leadTimes"`
	MaxParts                 int               `json:"maxParts"`
	MinOrderPln              float64           `json:"minOrderPln"`
	MinPartPricePln          float64           `json:"minPartPricePln"`
	OrderFeePln              float64           `json:"orderFeePln"`
	Processes                []CatalogProcess  `json:"processes"`
	QuantityChips            []int             `json:"quantityChips"`
	ShippingFlatPln          float64           `json:"shippingFlatPln"`
	VatRate                  float64           `json:"vatRate"`
}

// CheckoutResponse defines model for CheckoutResponse.
type CheckoutResponse struct {
	// Url Provider-hosted checkout URL to redirect the browser to
	Url string `json:"url"`
}

// ConfirmFileResponse defines model for ConfirmFileResponse.
type ConfirmFileResponse struct {
	FileId openapi_types.UUID `json:"fileId"`
	Stored bool               `json:"stored"`
}

// CreateFileRequest defines model for CreateFileRequest.
type CreateFileRequest struct {
	FileName  string                `json:"fileName"`
	Kind      CreateFileRequestKind `json:"kind"`
	Sha256    string                `json:"sha256"`
	SizeBytes int64                 `json:"sizeBytes"`
}

// CreateFileRequestKind defines model for CreateFileRequest.Kind.
type CreateFileRequestKind string

// CreateFileResponse defines model for CreateFileResponse.
type CreateFileResponse struct {
	AlreadyStored bool               `json:"alreadyStored"`
	FileId        openapi_types.UUID `json:"fileId"`

	// UploadUrl Presigned PUT URL; absent when alreadyStored is true
	UploadUrl *string `json:"uploadUrl,omitempty"`
}

// CreateOrderRequest defines model for CreateOrderRequest.
type CreateOrderRequest struct {
	BillingAddress *Address `json:"billingAddress,omitempty"`

	// CompanyName B2B only; presence together with nip implies always-invoice
	CompanyName *string `json:"companyName,omitempty"`

	// Country Supported EU shipping destinations
	Country EuCountry           `json:"country"`
	Email   openapi_types.Email `json:"email"`

	// InvoiceRequested B2C opt-in for a faktura VAT (B2B is always invoiced)
	InvoiceRequested *bool `json:"invoiceRequested,omitempty"`

	// Nip Polish NIP (10 digits); checksum validated server-side
	Nip *string `json:"nip,omitempty"`

	// QuoteId The quoteId returned by submitQuote, e.g. "Q-1A2B3C4D"
	QuoteId         string  `json:"quoteId"`
	ShippingAddress Address `json:"shippingAddress"`
}

// CreateOrderResponse defines model for CreateOrderResponse.
type CreateOrderResponse struct {
	// OrderId e.g. "O-1A2B3C4D"
	OrderId string `json:"orderId"`

	// StatusToken Bearer capability for the public status page (GET /api/v1/orders/track/{statusToken}); also embedded in the checkout success redirect.
	StatusToken string `json:"statusToken"`
}

// CustomerEmailRequest defines model for CustomerEmailRequest.
type CustomerEmailRequest struct {
	Email openapi_types.Email `json:"email"`
}

// DfmFlag defines model for DfmFlag.
type DfmFlag struct {
	Code DfmFlagCode `json:"code"`

	// Message English debug prose; the frontend renders from code+params.
	Message *string `json:"message,omitempty"`

	// Params Structured values for localized rendering, e.g. {"x": 340}.
	Params             *map[string]interface{} `json:"params,omitempty"`
	Severity           DfmFlagSeverity         `json:"severity"`
	SuggestedProcesses *[]ProcessId            `json:"suggestedProcesses,omitempty"`
}

// DfmFlagCode defines model for DfmFlag.Code.
type DfmFlagCode string

// DfmFlagSeverity defines model for DfmFlag.Severity.
type DfmFlagSeverity string

// DiscountTier defines model for DiscountTier.
type DiscountTier struct {
	Fraction float64 `json:"fraction"`
	Quantity int     `json:"quantity"`
}

// EraseCustomerRequest defines model for EraseCustomerRequest.
type EraseCustomerRequest struct {
	// DryRun Must be true — there is no destructive path (plan 09).
	DryRun bool                `json:"dryRun"`
	Email  openapi_types.Email `json:"email"`
}

// EuCountry Supported EU shipping destinations
type EuCountry string

// FdmModel defines model for FdmModel.
type FdmModel struct {
	InfillFraction          float64 `json:"infillFraction"`
	InfillGramsPerPrintHour float64 `json:"infillGramsPerPrintHour"`
	ShellGramsPerPrintHour  float64 `json:"shellGramsPerPrintHour"`
	ShellThicknessMm        float64 `json:"shellThicknessMm"`
}

// LeadTimeId defines model for LeadTimeId.
type LeadTimeId string

// ListOrdersResponse defines model for ListOrdersResponse.
type ListOrdersResponse struct {
	Orders []OrderSummary `json:"orders"`
}

// MakerworldError defines model for MakerworldError.
type MakerworldError struct {
	Code MakerworldErrorCode `json:"code"`
}

// MakerworldErrorCode defines model for MakerworldError.Code.
type MakerworldErrorCode string

// MakerworldFetchRequest defines model for MakerworldFetchRequest.
type MakerworldFetchRequest struct {
	DesignId  int64  `json:"designId"`
	ProfileId *int64 `json:"profileId,omitempty"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	Email openapi_types.Email `json:"email"`
	Role  MeResponseRole      `json:"role"`
}

// MeResponseRole defines model for MeResponse.Role.
type MeResponseRole string

// MeshMetrics Pricing-relevant subset of client-side mesh analysis
type MeshMetrics struct {
	BboxMm Vec3Mm `json:"bboxMm"`

	// Pieces Per-piece bounding boxes for multi-item 3MF files
	Pieces           *[]PieceMetrics `json:"pieces,omitempty"`
	SurfaceAreaCm2   float64         `json:"surfaceAreaCm2"`
	UsedHullFallback bool            `json:"usedHullFallback"`
	VolumeCm3        float64         `json:"volumeCm3"`
}

// OrderStatus Order lifecycle state; transitions are owned by the backend state machine (internal/orders).
type OrderStatus string

// OrderSummary defines model for OrderSummary.
type OrderSummary struct {
	CreatedAt time.Time `json:"createdAt"`

	// FileName First item's file name
	FileName      string     `json:"fileName"`
	GrossTotalPln float64    `json:"grossTotalPln"`
	LeadTime      LeadTimeId `json:"leadTime"`

	// OrderId e.g. "O-1A2B3C4D"
	OrderId   string `json:"orderId"`
	PartCount int    `json:"partCount"`

	// Status Order lifecycle state; transitions are owned by the backend state machine (internal/orders).
	Status OrderStatus `json:"status"`

	// StatusToken The order's public status-page capability — exposed here because this endpoint is session-guarded and the session proves ownership.
	StatusToken string `json:"statusToken"`
}

// OrderTotals defines model for OrderTotals.
type OrderTotals struct {
	FreeShipping     bool    `json:"freeShipping"`
	GrossTotalPln    float64 `json:"grossTotalPln"`
	MinOrderApplied  bool    `json:"minOrderApplied"`
	MinOrderTopUpPln float64 `json:"minOrderTopUpPln"`
	NetTotalPln      float64 `json:"netTotalPln"`
	OrderFeePln      float64 `json:"orderFeePln"`
	PartsSubtotalPln float64 `json:"partsSubtotalPln"`
	ShippingPln      float64 `json:"shippingPln"`
	VatPln           float64 `json:"vatPln"`
}

// PartQuote defines model for PartQuote.
type PartQuote struct {
	BillableVolumeCm3  float64         `json:"billableVolumeCm3"`
	Blocked            bool            `json:"blocked"`
	Breakdown          []BreakdownLine `json:"breakdown"`
	DfmFlags           []DfmFlag       `json:"dfmFlags"`
	DiscountFraction   float64         `json:"discountFraction"`
	LeadTimeMultiplier float64         `json:"leadTimeMultiplier"`
	LineTotalPln       float64         `json:"lineTotalPln"`

	// PieceCount Present only for multi-piece 3MF parts
	PieceCount *int `json:"pieceCount,omitempty"`

	// Plates Present only for multi-piece 3MF parts
	Plates      *int         `json:"plates,omitempty"`
	PriceBreaks []PriceBreak `json:"priceBreaks"`

	// PrintHours Estimated print time in hours
	PrintHours   float64 `json:"printHours"`
	UnitBasePln  float64 `json:"unitBasePln"`
	UnitPricePln float64 `json:"unitPricePln"`

	// WeightG Estimated print weight (shell + infill model)
	WeightG float64 `json:"weightG"`
}

// PieceMetrics defines model for PieceMetrics.
type PieceMetrics struct {
	BboxMm Vec3Mm `json:"bboxMm"`
}

// PriceBreak defines model for PriceBreak.
type PriceBreak struct {
	DiscountFraction float64 `json:"discountFraction"`
	Quantity         int     `json:"quantity"`
	UnitPricePln     float64 `json:"unitPricePln"`
}

// PriceCompareRequest One part without a process — process is the loop variable
type PriceCompareRequest struct {
	LeadTime LeadTimeId `json:"leadTime"`

	// Metrics Pricing-relevant subset of client-side mesh analysis
	Metrics  MeshMetrics `json:"metrics"`
	Quantity int         `json:"quantity"`
}

// PriceCompareResponse defines model for PriceCompareResponse.
type PriceCompareResponse struct {
	Rows []PriceCompareRow `json:"rows"`
}

// PriceCompareRow defines model for PriceCompareRow.
type PriceCompareRow struct {
	Process ProcessId `json:"process"`
	Quote   PartQuote `json:"quote"`
}

// PricePart defines model for PricePart.
type PricePart struct {
	LeadTime LeadTimeId `json:"leadTime"`

	// Metrics Pricing-relevant subset of client-side mesh analysis
	Metrics  MeshMetrics `json:"metrics"`
	Process  ProcessId   `json:"process"`
	Quantity int         `json:"quantity"`
}

// PriceRequest defines model for PriceRequest.
type PriceRequest struct {
	Parts []PricePart `json:"parts"`
}

// PriceResponse defines model for PriceResponse.
type PriceResponse struct {
	Parts  []PartQuote `json:"parts"`
	Totals OrderTotals `json:"totals"`
}

// PricingConfig Mirrors the Go pricing.Config struct's JSON exactly — Go field names (the struct has no json tags; Build keeps its lowercase x/y/z tags). The drift-guard test fails the build if the struct and this schema diverge.
type PricingConfig struct {
	DiscountTiers            []PricingDiscountTier `json:"DiscountTiers"`
	ExtraPlateFeePln         float64               `json:"ExtraPlateFeePln"`
	Fdm                      PricingFdmModel       `json:"Fdm"`
	FreeShippingThresholdPln float64               `json:"FreeShippingThresholdPln"`
	LeadTimes                []PricingLeadTimeDef  `json:"LeadTimes"`
	MinBillableVolumeCm3     float64               `json:"MinBillableVolumeCm3"`
	MinFeatureMm             float64               `json:"MinFeatureMm"`
	MinOrderPln              float64               `json:"MinOrderPln"`
	MinPartPricePln          float64               `json:"MinPartPricePln"`
	OrderFeePln              float64               `json:"OrderFeePln"`
	PlateGutterMm            float64               `json:"PlateGutterMm"`
	Processes                []PricingProcessDef   `json:"Processes"`
	SameDayCutoffHour        int                   `json:"SameDayCutoffHour"`
	ShippingFlatPln          float64               `json:"ShippingFlatPln"`
	VatRate                  float64               `json:"VatRate"`
}

// PricingConfigSnapshot defines model for PricingConfigSnapshot.
type PricingConfigSnapshot struct {
	// Config Mirrors the Go pricing.Config struct's JSON exactly — Go field names (the struct has no json tags; Build keeps its lowercase x/y/z tags). The drift-guard test fails the build if the struct and this schema diverge.
	Config    PricingConfig      `json:"config"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	IsActive  bool               `json:"isActive"`
	Label     string             `json:"label"`
}

// PricingConfigSnapshotMeta defines model for PricingConfigSnapshotMeta.
type PricingConfigSnapshotMeta struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	IsActive  bool               `json:"isActive"`
	Label     string             `json:"label"`
}

// PricingDiscountTier defines model for PricingDiscountTier.
type PricingDiscountTier struct {
	Fraction float64 `json:"Fraction"`
	Quantity float64 `json:"Quantity"`
}

// PricingFdmModel defines model for PricingFdmModel.
type PricingFdmModel struct {
	InfillFraction          float64 `json:"InfillFraction"`
	InfillGramsPerPrintHour float64 `json:"InfillGramsPerPrintHour"`
	ShellGramsPerPrintHour  float64 `json:"ShellGramsPerPrintHour"`
	ShellThicknessMm        float64 `json:"ShellThicknessMm"`
}

// PricingLeadTimeDef defines model for PricingLeadTimeDef.
type PricingLeadTimeDef struct {
	BusinessDays int     `json:"BusinessDays"`
	ID           string  `json:"ID"`
	Mult         float64 `json:"Mult"`
}

// PricingProcessDef defines model for PricingProcessDef.
type PricingProcessDef struct {
	Build struct {
		X float64 `json:"x"`
		Y float64 `json:"y"`
		Z float64 `json:"z"`
	} `json:"Build"`
	DensityGCm3 float64 `json:"DensityGCm3"`
	Factor      float64 `json:"Factor"`
	ID          string  `json:"ID"`
	Label       string  `json:"Label"`
	PlnPerHour  float64 `json:"PlnPerHour"`
	PlnPerKg    float64 `json:"PlnPerKg"`
}

// ProcessId defines model for ProcessId.
type ProcessId string

// ReplacePricingConfigRequest defines model for ReplacePricingConfigRequest.
type ReplacePricingConfigRequest struct {
	// Config Mirrors the Go pricing.Config struct's JSON exactly — Go field names (the struct has no json tags; Build keeps its lowercase x/y/z tags). The drift-guard test fails the build if the struct and this schema diverge.
	Config PricingConfig `json:"config"`
	Label  string        `json:"label"`
}

// ReplacePricingConfigResponse defines model for ReplacePricingConfigResponse.
type ReplacePricingConfigResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// RequestCodeRequest defines model for RequestCodeRequest.
type RequestCodeRequest struct {
	Email openapi_types.Email `json:"email"`
}

// ShipDate defines model for ShipDate.
type ShipDate struct {
	Date                CalDate `json:"date"`
	DispatchStartsToday bool    `json:"dispatchStartsToday"`

	// Label e.g. "Thu 16 Jul" (canonical engine label; UI formats the date per locale)
	Label    string     `json:"label"`
	LeadTime LeadTimeId `json:"leadTime"`
}

// ShipDatesResponse defines model for ShipDatesResponse.
type ShipDatesResponse struct {
	ShipDates []ShipDate `json:"shipDates"`
}

// StepQuoteRequest defines model for StepQuoteRequest.
type StepQuoteRequest struct {
	Email    openapi_types.Email `json:"email"`
	FileName string              `json:"fileName"`
	FileSize int                 `json:"fileSize"`
}

// StepQuoteResponse defines model for StepQuoteResponse.
type StepQuoteResponse struct {
	// RequestId e.g. "STEP-1A2B3C4D"
	RequestId string `json:"requestId"`
}

// SubmitQuotePart defines model for SubmitQuotePart.
type SubmitQuotePart struct {
	// FileId The stored file backing this part (plan 02). When present the server verifies it exists with a matching hash and links it.
	FileId   *openapi_types.UUID `json:"fileId,omitempty"`
	FileName string              `json:"fileName"`
	Hash     string              `json:"hash"`
	LeadTime LeadTimeId          `json:"leadTime"`

	// Metrics Pricing-relevant subset of client-side mesh analysis
	Metrics  MeshMetrics `json:"metrics"`
	Process  ProcessId   `json:"process"`
	Quantity int         `json:"quantity"`
}

// SubmitQuoteRequest defines model for SubmitQuoteRequest.
type SubmitQuoteRequest struct {
	// ClientGrossTotalPln The gross total the client displayed, for mismatch telemetry. The server's own computation is authoritative.
	ClientGrossTotalPln *float64 `json:"clientGrossTotalPln,omitempty"`

	// Country Supported EU shipping destinations
	Country EuCountry           `json:"country"`
	Email   openapi_types.Email `json:"email"`

	// Locale UI locale at submit time; persisted for downstream emails and invoices (plans 05/06 read it).
	Locale *SubmitQuoteRequestLocale `json:"locale,omitempty"`
	Parts  []SubmitQuotePart         `json:"parts"`
}

// SubmitQuoteRequestLocale UI locale at submit time; persisted for downstream emails and invoices (plans 05/06 read it).
type SubmitQuoteRequestLocale string

// SubmitQuoteResponse defines model for SubmitQuoteResponse.
type SubmitQuoteResponse struct {
	// QuoteId e.g. "Q-1A2B3C4D"
	QuoteId string      `json:"quoteId"`
	Totals  OrderTotals `json:"totals"`
}

// TrackedOrder defines model for TrackedOrder.
type TrackedOrder struct {
	CreatedAt time.Time          `json:"createdAt"`
	Items     []TrackedOrderItem `json:"items"`
	OrderId   string             `json:"orderId"`
	PaidAt    *time.Time         `json:"paidAt,omitempty"`

	// Status Order lifecycle state; transitions are owned by the backend state machine (internal/orders).
	Status OrderStatus `json:"status"`
	Totals OrderTotals `json:"totals"`
}

// TrackedOrderItem defines model for TrackedOrderItem.
type TrackedOrderItem struct {
	FileName     string     `json:"fileName"`
	LeadTime     LeadTimeId `json:"leadTime"`
	LineTotalPln float64    `json:"lineTotalPln"`
	Process      ProcessId  `json:"process"`
	Quantity     int        `json:"quantity"`
	UnitPricePln float64    `json:"unitPricePln"`
}

// TransitionOrderRequest defines model for TransitionOrderRequest.
type TransitionOrderRequest struct {
	// To Order lifecycle state; transitions are owned by the backend state machine (internal/orders).
	To OrderStatus `json:"to"`

	// TrackingNumber Required for to=shipped; stored on the order.
	TrackingNumber *string `json:"trackingNumber,omitempty"`
}

// UpdateStepRequestStatusRequest defines model for UpdateStepRequestStatusRequest.
type UpdateStepRequestStatusRequest struct {
	Status UpdateStepRequestStatusRequestStatus `json:"status"`
}

// UpdateStepRequestStatusRequestStatus defines model for UpdateStepRequestStatusRequest.Status.
type UpdateStepRequestStatusRequestStatus string

// Vec3Mm defines model for Vec3Mm.
type Vec3Mm struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	Z float64 `json:"z"`
}

// VerifyCodeRequest defines model for VerifyCodeRequest.
type VerifyCodeRequest struct {
	Code  string              `json:"code"`
	Email openapi_types.Email `json:"email"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ApiError

// Conflict defines model for Conflict.
type Conflict = ApiError

// Forbidden defines model for Forbidden.
type Forbidden = ApiError

// NotFound defines model for NotFound.
type NotFound = ApiError

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = ApiError

// AdminLookupCustomerParams defines parameters for AdminLookupCustomer.
type AdminLookupCustomerParams struct {
	Email openapi_types.Email `form:"email" json:"email"`
}

// AdminListOrdersParams defines parameters for AdminListOrders.
type AdminListOrdersParams struct {
	Status *OrderStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int         `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int         `form:"offset,omitempty" json:"offset,omitempty"`
}

// AdminListStepRequestsParams defines parameters for AdminListStepRequests.
type AdminListStepRequestsParams struct {
	Status *AdminListStepRequestsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// AdminListStepRequestsParamsStatus defines parameters for AdminListStepRequests.
type AdminListStepRequestsParamsStatus string

// AdminEraseCustomerJSONRequestBody defines body for AdminEraseCustomer for application/json ContentType.
type AdminEraseCustomerJSONRequestBody = EraseCustomerRequest

// AdminExportCustomerJSONRequestBody defines body for AdminExportCustomer for application/json ContentType.
type AdminExportCustomerJSONRequestBody = CustomerEmailRequest

// AdminTransitionOrderJSONRequestBody defines body for AdminTransitionOrder for application/json ContentType.
type AdminTransitionOrderJSONRequestBody = TransitionOrderRequest

// AdminReplacePricingConfigJSONRequestBody defines body for AdminReplacePricingConfig for application/json ContentType.
type AdminReplacePricingConfigJSONRequestBody = ReplacePricingConfigRequest

// AdminUpdateStepRequestStatusJSONRequestBody defines body for AdminUpdateStepRequestStatus for application/json ContentType.
type AdminUpdateStepRequestStatusJSONRequestBody = UpdateStepRequestStatusRequest

// RequestLoginCodeJSONRequestBody defines body for RequestLoginCode for application/json ContentType.
type RequestLoginCodeJSONRequestBody = RequestCodeRequest

// VerifyLoginCodeJSONRequestBody defines body for VerifyLoginCode for application/json ContentType.
type VerifyLoginCodeJSONRequestBody = VerifyCodeRequest

// CreateFileUploadJSONRequestBody defines body for CreateFileUpload for application/json ContentType.
type CreateFileUploadJSONRequestBody = CreateFileRequest

// FetchMakerworldModelJSONRequestBody defines body for FetchMakerworldModel for application/json ContentType.
type FetchMakerworldModelJSONRequestBody = MakerworldFetchRequest

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// PriceJSONRequestBody defines body for Price for application/json ContentType.
type PriceJSONRequestBody = PriceRequest

// PriceCompareJSONRequestBody defines body for PriceCompare for application/json ContentType.
type PriceCompareJSONRequestBody = PriceCompareRequest

// SubmitQuoteJSONRequestBody defines body for SubmitQuote for application/json ContentType.
type SubmitQuoteJSONRequestBody = SubmitQuoteRequest

// SubmitStepQuoteJSONRequestBody defines body for SubmitStepQuote for application/json ContentType.
type SubmitStepQuoteJSONRequestBody = StepQuoteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Customer lookup by email (admin only): user account, orders, quotes, STEP requests, and linked files. Guests included — email is the join key. Unknown emails return empty arrays, not 404.
	// (GET /api/v1/admin/customers)
	AdminLookupCustomer(w http.ResponseWriter, r *http.Request, params AdminLookupCustomerParams)
	// GDPR erasure — DRY-RUN ONLY (admin only). Reports what would be deleted vs retained (invoice-retention carve-out, plan 09). dryRun must be true; anything else is 400 erase_not_enabled. There is no destructive code path.
	// (POST /api/v1/admin/customers/erase)
	AdminEraseCustomer(w http.ResponseWriter, r *http.Request)
	// GDPR data-portability export (admin only): everything keyed to an email as one JSON bundle — orders in full detail shape (items, payments, invoices). The frontend downloads it as a blob.
	// (POST /api/v1/admin/customers/export)
	AdminExportCustomer(w http.ResponseWriter, r *http.Request)
	// Board KPI strip (admin only): today vs yesterday order counts and gross (Warsaw calendar), per-status counts, overdue open orders (engine-derived ship-by), new STEP requests, and a 14-day orders sparkline (oldest first, zero-filled, ending today).
	// (GET /api/v1/admin/ops/stats)
	AdminGetOpsStats(w http.ResponseWriter, r *http.Request)
	// "What must ship today" (admin only): paid and in_production orders whose derived ship-by date is today or earlier (Warsaw business calendar), soonest first. Ship dates recompute from the lead-time engine with paid_at as the anchor — nothing is denormalized.
	// (GET /api/v1/admin/ops/today)
	AdminGetOpsToday(w http.ResponseWriter, r *http.Request)
	// Orders board list (admin only), newest first. shipBy/overdue are derived from the lead-time engine with paid_at as the anchor; dfmCodes collects warn/block/manual_verify flag codes across items.
	// (GET /api/v1/admin/orders)
	AdminListOrders(w http.ResponseWriter, r *http.Request, params AdminListOrdersParams)
	// Full order detail for the operator (admin only): addresses, NIP, status capability token, totals, line items with their frozen pricing snapshots, and the payment/invoice ledgers. No email log (plan 06).
	// (GET /api/v1/admin/orders/{orderId})
	AdminGetOrder(w http.ResponseWriter, r *http.Request, orderId string)
	// Download a stored model file that is part of the order (admin only) — production needs the actual geometry. 404 file_not_found when the file is not attached to this order (or was deleted).
	// (GET /api/v1/admin/orders/{orderId}/files/{fileId})
	AdminDownloadOrderFile(w http.ResponseWriter, r *http.Request, orderId string, fileId openapi_types.UUID)
	// Refund a paid order (admin only). The provider refund is requested here but the status flip to 'refunded' happens in the payment-event pipeline (request/confirm split — same rule as payment).
	// (POST /api/v1/admin/orders/{orderId}/refund)
	RefundOrder(w http.ResponseWriter, r *http.Request, orderId string)
	// Move an order along the lifecycle (admin only). Only board transitions are accepted — paid/refunded flip exclusively through the payment pipeline, so draft/paid/refunded targets get 400 transition_not_allowed. Shipped requires a tracking number (400 tracking_required). Illegal edges get 409 order_wrong_state.
	// (POST /api/v1/admin/orders/{orderId}/transition)
	AdminTransitionOrder(w http.ResponseWriter, r *http.Request, orderId string)
	// Active pricing config plus version history (admin only). The active snapshot is what prices new quotes right now — swaps are live, no deploy needed.
	// (GET /api/v1/admin/pricing-config)
	AdminGetPricingConfig(w http.ResponseWriter, r *http.Request)
	// Publish a new pricing config snapshot (admin only): validated against the Go engine's structure (formula shape is not editable), persisted as the new active row, and swapped into the running process atomically. Existing quotes/orders keep their original snapshot.
	// (POST /api/v1/admin/pricing-config)
	AdminReplacePricingConfig(w http.ResponseWriter, r *http.Request)
	// Read one historical pricing config snapshot (admin only)
	// (GET /api/v1/admin/pricing-config/{id})
	AdminGetPricingConfigSnapshot(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// STEP manual-quote queue (admin only), newest first
	// (GET /api/v1/admin/step-requests)
	AdminListStepRequests(w http.ResponseWriter, r *http.Request, params AdminListStepRequestsParams)
	// Download the STEP file attached to the request (admin only). 404 file_not_found when no file is attached or its bytes are not stored.
	// (GET /api/v1/admin/step-requests/{requestId}/file)
	AdminDownloadStepRequestFile(w http.ResponseWriter, r *http.Request, requestId string)
	// Advance a STEP request to quoted or closed (admin only). Closed is terminal — any further change is 409 step_request_wrong_state.
	// (POST /api/v1/admin/step-requests/{requestId}/status)
	AdminUpdateStepRequestStatus(w http.ResponseWriter, r *http.Request, requestId string)
	// Delete the current session and clear the cookie
	// (POST /api/v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Current session's identity (session restore for the frontend)
	// (GET /api/v1/auth/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Email a 6-digit one-time login code. Always returns 204 — whether the email has orders or not, and whether the resend throttle skipped sending — so the endpoint never reveals which emails exist. 400 only for a malformed email.
	// (POST /api/v1/auth/request-code)
	RequestLoginCode(w http.ResponseWriter, r *http.Request)
	// Verify a 6-digit login code. On success sets the iq_session cookie (httpOnly, SameSite=Lax) and returns 204. Codes are single-use, expire after 10 minutes, and allow at most 5 attempts.
	// (POST /api/v1/auth/verify-code)
	VerifyLoginCode(w http.ResponseWriter, r *http.Request)
	// Pricing catalog for display (processes, lead times, fees)
	// (GET /api/v1/config)
	GetConfig(w http.ResponseWriter, r *http.Request)
	// Reserve a file record and get a presigned upload URL (dedups by hash)
	// (POST /api/v1/files)
	CreateFileUpload(w http.ResponseWriter, r *http.Request)
	// Confirm a presigned upload completed; verifies the stored object size
	// (POST /api/v1/files/{fileId}/confirm)
	ConfirmFileUpload(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID)
	// Download a MakerWorld model's 3MF via Bambu Cloud
	// (POST /api/v1/makerworld/fetch)
	FetchMakerworldModel(w http.ResponseWriter, r *http.Request)
	// List the signed-in user's orders, newest first. Identity is derived from the session server-side; guest checkouts appear via their email.
	// (GET /api/v1/orders)
	ListOrders(w http.ResponseWriter, r *http.Request)
	// Create a draft order from a persisted quote. The client sends no prices — every money value is copied verbatim from the stored, server-recomputed quote rows (anti-tamper boundary).
	// (POST /api/v1/orders)
	CreateOrder(w http.ResponseWriter, r *http.Request)
	// Public order status view. The statusToken (returned by createOrder and embedded in the post-payment redirect) is the bearer capability; the response is redacted — no internal ids, no raw provider objects, no PII beyond the line items.
	// (GET /api/v1/orders/track/{statusToken})
	TrackOrder(w http.ResponseWriter, r *http.Request, statusToken string)
	// Create (or return the live) payment-provider checkout session for a draft order. The returned URL is provider-hosted (Stripe Checkout in plan 18, a stub page while PAYMENTS_PROVIDER=stub) — the browser redirects to it and never asserts payment itself.
	// (POST /api/v1/orders/{orderId}/checkout)
	CreateOrderCheckout(w http.ResponseWriter, r *http.Request, orderId string)
	// Price a set of parts and compute order totals
	// (POST /api/v1/price)
	Price(w http.ResponseWriter, r *http.Request)
	// Unit price of one part across every process in the catalog, for the materials-compare UI. Blocked (oversized) processes are returned with blocked=true rather than omitted.
	// (POST /api/v1/price/compare)
	PriceCompare(w http.ResponseWriter, r *http.Request)
	// Submit an order request; prices are recomputed server-side
	// (POST /api/v1/quotes)
	SubmitQuote(w http.ResponseWriter, r *http.Request)
	// Read back a submitted quote by its id. The id is an unguessable capability token (the quoteId returned by submitQuote); the response is pricing-only and carries no customer PII.
	// (GET /api/v1/quotes/{id})
	GetQuote(w http.ResponseWriter, r *http.Request, id string)
	// Estimated ship dates per lead time (Europe/Warsaw clock)
	// (GET /api/v1/ship-dates)
	GetShipDates(w http.ResponseWriter, r *http.Request)
	// Request a manual quote for a STEP file
	// (POST /api/v1/step-quotes)
	SubmitStepQuote(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Customer lookup by email (admin only): user account, orders, quotes, STEP requests, and linked files. Guests included — email is the join key. Unknown emails return empty arrays, not 404.
// (GET /api/v1/admin/customers)
func (_ Unimplemented) AdminLookupCustomer(w http.ResponseWriter, r *http.Request, params AdminLookupCustomerParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GDPR erasure — DRY-RUN ONLY (admin only). Reports what would be deleted vs retained (invoice-retention carve-out, plan 09). dryRun must be true; anything else is 400 erase_not_enabled. There is no destructive code path.
// (POST /api/v1/admin/customers/erase)
func (_ Unimplemented) AdminEraseCustomer(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GDPR data-portability export (admin only): everything keyed to an email as one JSON bundle — orders in full detail shape (items, payments, invoices). The frontend downloads it as a blob.
// (POST /api/v1/admin/customers/export)
func (_ Unimplemented) AdminExportCustomer(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Board KPI strip (admin only): today vs yesterday order counts and gross (Warsaw calendar), per-status counts, overdue open orders (engine-derived ship-by), new STEP requests, and a 14-day orders sparkline (oldest first, zero-filled, ending today).
// (GET /api/v1/admin/ops/stats)
func (_ Unimplemented) AdminGetOpsStats(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// "What must ship today" (admin only): paid and in_production orders whose derived ship-by date is today or earlier (Warsaw business calendar), soonest first. Ship dates recompute from the lead-time engine with paid_at as the anchor — nothing is denormalized.
// (GET /api/v1/admin/ops/today)
func (_ Unimplemented) AdminGetOpsToday(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Orders board list (admin only), newest first. shipBy/overdue are derived from the lead-time engine with paid_at as the anchor; dfmCodes collects warn/block/manual_verify flag codes across items.
// (GET /api/v1/admin/orders)
func (_ Unimplemented) AdminListOrders(w http.ResponseWriter, r *http.Request, params AdminListOrdersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Full order detail for the operator (admin only): addresses, NIP, status capability token, totals, line items with their frozen pricing snapshots, and the payment/invoice ledgers. No email log (plan 06).
// (GET /api/v1/admin/orders/{orderId})
func (_ Unimplemented) AdminGetOrder(w http.ResponseWriter, r *http.Request, orderId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download a stored model file that is part of the order (admin only) — production needs the actual geometry. 404 file_not_found when the file is not attached to this order (or was deleted).
// (GET /api/v1/admin/orders/{orderId}/files/{fileId})
func (_ Unimplemented) AdminDownloadOrderFile(w http.ResponseWriter, r *http.Request, orderId string, fileId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refund a paid order (admin only). The provider refund is requested here but the status flip to 'refunded' happens in the payment-event pipeline (request/confirm split — same rule as payment).
// (POST /api/v1/admin/orders/{orderId}/refund)
func (_ Unimplemented) RefundOrder(w http.ResponseWriter, r *http.Request, orderId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Move an order along the lifecycle (admin only). Only board transitions are accepted — paid/refunded flip exclusively through the payment pipeline, so draft/paid/refunded targets get 400 transition_not_allowed. Shipped requires a tracking number (400 tracking_required). Illegal edges get 409 order_wrong_state.
// (POST /api/v1/admin/orders/{orderId}/transition)
func (_ Unimplemented) AdminTransitionOrder(w http.ResponseWriter, r *http.Request, orderId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Active pricing config plus version history (admin only). The active snapshot is what prices new quotes right now — swaps are live, no deploy needed.
// (GET /api/v1/admin/pricing-config)
func (_ Unimplemented) AdminGetPricingConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Publish a new pricing config snapshot (admin only): validated against the Go engine's structure (formula shape is not editable), persisted as the new active row, and swapped into the running process atomically. Existing quotes/orders keep their original snapshot.
// (POST /api/v1/admin/pricing-config)
func (_ Unimplemented) AdminReplacePricingConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read one historical pricing config snapshot (admin only)
// (GET /api/v1/admin/pricing-config/{id})
func (_ Unimplemented) AdminGetPricingConfigSnapshot(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// STEP manual-quote queue (admin only), newest first
// (GET /api/v1/admin/step-requests)
func (_ Unimplemented) AdminListStepRequests(w http.ResponseWriter, r *http.Request, params AdminListStepRequestsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download the STEP file attached to the request (admin only). 404 file_not_found when no file is attached or its bytes are not stored.
// (GET /api/v1/admin/step-requests/{requestId}/file)
func (_ Unimplemented) AdminDownloadStepRequestFile(w http.ResponseWriter, r *http.Request, requestId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Advance a STEP request to quoted or closed (admin only). Closed is terminal — any further change is 409 step_request_wrong_state.
// (POST /api/v1/admin/step-requests/{requestId}/status)
func (_ Unimplemented) AdminUpdateStepRequestStatus(w http.ResponseWriter, r *http.Request, requestId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete the current session and clear the cookie
// (POST /api/v1/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Current session's identity (session restore for the frontend)
// (GET /api/v1/auth/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Email a 6-digit one-time login code. Always returns 204 — whether the email has orders or not, and whether the resend throttle skipped sending — so the endpoint never reveals which emails exist. 400 only for a malformed email.
// (POST /api/v1/auth/request-code)
func (_ Unimplemented) RequestLoginCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify a 6-digit login code. On success sets the iq_session cookie (httpOnly, SameSite=Lax) and returns 204. Codes are single-use, expire after 10 minutes, and allow at most 5 attempts.
// (POST /api/v1/auth/verify-code)
func (_ Unimplemented) VerifyLoginCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Pricing catalog for display (processes, lead times, fees)
// (GET /api/v1/config)
func (_ Unimplemented) GetConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reserve a file record and get a presigned upload URL (dedups by hash)
// (POST /api/v1/files)
func (_ Unimplemented) CreateFileUpload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Confirm a presigned upload completed; verifies the stored object size
// (POST /api/v1/files/{fileId}/confirm)
func (_ Unimplemented) ConfirmFileUpload(w http.ResponseWriter, r *http.Request, fileId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download a MakerWorld model's 3MF via Bambu Cloud
// (POST /api/v1/makerworld/fetch)
func (_ Unimplemented) FetchMakerworldModel(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List the signed-in user's orders, newest first. Identity is derived from the session server-side; guest checkouts appear via their email.
// (GET /api/v1/orders)
func (_ Unimplemented) ListOrders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a draft order from a persisted quote. The client sends no prices — every money value is copied verbatim from the stored, server-recomputed quote rows (anti-tamper boundary).
// (POST /api/v1/orders)
func (_ Unimplemented) CreateOrder(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Public order status view. The statusToken (returned by createOrder and embedded in the post-payment redirect) is the bearer capability; the response is redacted — no internal ids, no raw provider objects, no PII beyond the line items.
// (GET /api/v1/orders/track/{statusToken})
func (_ Unimplemented) TrackOrder(w http.ResponseWriter, r *http.Request, statusToken string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create (or return the live) payment-provider checkout session for a draft order. The returned URL is provider-hosted (Stripe Checkout in plan 18, a stub page while PAYMENTS_PROVIDER=stub) — the browser redirects to it and never asserts payment itself.
// (POST /api/v1/orders/{orderId}/checkout)
func (_ Unimplemented) CreateOrderCheckout(w http.ResponseWriter, r *http.Request, orderId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Price a set of parts and compute order totals
// (POST /api/v1/price)
func (_ Unimplemented) Price(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Unit price of one part across every process in the catalog, for the materials-compare UI. Blocked (oversized) processes are returned with blocked=true rather than omitted.
// (POST /api/v1/price/compare)
func (_ Unimplemented) PriceCompare(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit an order request; prices are recomputed server-side
// (POST /api/v1/quotes)
func (_ Unimplemented) SubmitQuote(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Read back a submitted quote by its id. The id is an unguessable capability token (the quoteId returned by submitQuote); the response is pricing-only and carries no customer PII.
// (GET /api/v1/quotes/{id})
func (_ Unimplemented) GetQuote(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Estimated ship dates per lead time (Europe/Warsaw clock)
// (GET /api/v1/ship-dates)
func (_ Unimplemented) GetShipDates(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request a manual quote for a STEP file
// (POST /api/v1/step-quotes)
func (_ Unimplemented) SubmitStepQuote(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AdminLookupCustomer operation middleware
func (siw *ServerInterfaceWrapper) AdminLookupCustomer(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AdminLookupCustomerParams

	// ------------- Required query parameter "email" -------------

	if paramValue := r.URL.Query().Get("email"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "email"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "email", r.URL.Query(), &params.Email)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "email", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminLookupCustomer(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminEraseCustomer operation middleware
func (siw *ServerInterfaceWrapper) AdminEraseCustomer(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminEraseCustomer(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminExportCustomer operation middleware
func (siw *ServerInterfaceWrapper) AdminExportCustomer(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminExportCustomer(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminGetOpsStats operation middleware
func (siw *ServerInterfaceWrapper) AdminGetOpsStats(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminGetOpsStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminGetOpsToday operation middleware
func (siw *ServerInterfaceWrapper) AdminGetOpsToday(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminGetOpsToday(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminListOrders operation middleware
func (siw *ServerInterfaceWrapper) AdminListOrders(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AdminListOrdersParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminListOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminGetOrder operation middleware
func (siw *ServerInterfaceWrapper) AdminGetOrder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orderId" -------------
	var orderId string

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", chi.URLParam(r, "orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminGetOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminDownloadOrderFile operation middleware
func (siw *ServerInterfaceWrapper) AdminDownloadOrderFile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orderId" -------------
	var orderId string

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", chi.URLParam(r, "orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	// ------------- Path parameter "fileId" -------------
	var fileId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "fileId", chi.URLParam(r, "fileId"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fileId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminDownloadOrderFile(w, r, orderId, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefundOrder operation middleware
func (siw *ServerInterfaceWrapper) RefundOrder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orderId" -------------
	var orderId string

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", chi.URLParam(r, "orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefundOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminTransitionOrder operation middleware
func (siw *ServerInterfaceWrapper) AdminTransitionOrder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orderId" -------------
	var orderId string

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", chi.URLParam(r, "orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminTransitionOrder(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminGetPricingConfig operation middleware
func (siw *ServerInterfaceWrapper) AdminGetPricingConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminGetPricingConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminReplacePricingConfig operation middleware
func (siw *ServerInterfaceWrapper) AdminReplacePricingConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminReplacePricingConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminGetPricingConfigSnapshot operation middleware
func (siw *ServerInterfaceWrapper) AdminGetPricingConfigSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminGetPricingConfigSnapshot(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminListStepRequests operation middleware
func (siw *ServerInterfaceWrapper) AdminListStepRequests(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AdminListStepRequestsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminListStepRequests(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminDownloadStepRequestFile operation middleware
func (siw *ServerInterfaceWrapper) AdminDownloadStepRequestFile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "requestId" -------------
	var requestId string

	err = runtime.BindStyledParameterWithOptions("simple", "requestId", chi.URLParam(r, "requestId"), &requestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "requestId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminDownloadStepRequestFile(w, r, requestId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminUpdateStepRequestStatus operation middleware
func (siw *ServerInterfaceWrapper) AdminUpdateStepRequestStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "requestId" -------------
	var requestId string

	err = runtime.BindStyledParameterWithOptions("simple", "requestId", chi.URLParam(r, "requestId"), &requestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "requestId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminUpdateStepRequestStatus(w, r, requestId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestLoginCode operation middleware
func (siw *ServerInterfaceWrapper) RequestLoginCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestLoginCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyLoginCode operation middleware
func (siw *ServerInterfaceWrapper) VerifyLoginCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyLoginCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConfig operation middleware
func (siw *ServerInterfaceWrapper) GetConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateFileUpload operation middleware
func (siw *ServerInterfaceWrapper) CreateFileUpload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateFileUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmFileUpload operation middleware
func (siw *ServerInterfaceWrapper) ConfirmFileUpload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "fileId" -------------
	var fileId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "fileId", chi.URLParam(r, "fileId"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fileId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmFileUpload(w, r, fileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FetchMakerworldModel operation middleware
func (siw *ServerInterfaceWrapper) FetchMakerworldModel(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FetchMakerworldModel(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrders operation middleware
func (siw *ServerInterfaceWrapper) ListOrders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrder(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TrackOrder operation middleware
func (siw *ServerInterfaceWrapper) TrackOrder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "statusToken" -------------
	var statusToken string

	err = runtime.BindStyledParameterWithOptions("simple", "statusToken", chi.URLParam(r, "statusToken"), &statusToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "statusToken", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TrackOrder(w, r, statusToken)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrderCheckout operation middleware
func (siw *ServerInterfaceWrapper) CreateOrderCheckout(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "orderId" -------------
	var orderId string

	err = runtime.BindStyledParameterWithOptions("simple", "orderId", chi.URLParam(r, "orderId"), &orderId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "orderId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrderCheckout(w, r, orderId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Price operation middleware
func (siw *ServerInterfaceWrapper) Price(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Price(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PriceCompare operation middleware
func (siw *ServerInterfaceWrapper) PriceCompare(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PriceCompare(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitQuote operation middleware
func (siw *ServerInterfaceWrapper) SubmitQuote(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitQuote(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetQuote operation middleware
func (siw *ServerInterfaceWrapper) GetQuote(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetQuote(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetShipDates operation middleware
func (siw *ServerInterfaceWrapper) GetShipDates(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetShipDates(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitStepQuote operation middleware
func (siw *ServerInterfaceWrapper) SubmitStepQuote(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitStepQuote(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/customers", wrapper.AdminLookupCustomer)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/customers/erase", wrapper.AdminEraseCustomer)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/customers/export", wrapper.AdminExportCustomer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/ops/stats", wrapper.AdminGetOpsStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/ops/today", wrapper.AdminGetOpsToday)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/orders", wrapper.AdminListOrders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/orders/{orderId}", wrapper.AdminGetOrder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/orders/{orderId}/files/{fileId}", wrapper.AdminDownloadOrderFile)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/orders/{orderId}/refund", wrapper.RefundOrder)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/orders/{orderId}/transition", wrapper.AdminTransitionOrder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/pricing-config", wrapper.AdminGetPricingConfig)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/pricing-config", wrapper.AdminReplacePricingConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/pricing-config/{id}", wrapper.AdminGetPricingConfigSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/step-requests", wrapper.AdminListStepRequests)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/step-requests/{requestId}/file", wrapper.AdminDownloadStepRequestFile)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/step-requests/{requestId}/status", wrapper.AdminUpdateStepRequestStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/request-code", wrapper.RequestLoginCode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/verify-code", wrapper.VerifyLoginCode)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/config", wrapper.GetConfig)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/files", wrapper.CreateFileUpload)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/files/{fileId}/confirm", wrapper.ConfirmFileUpload)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/makerworld/fetch", wrapper.FetchMakerworldModel)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/orders", wrapper.ListOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/orders", wrapper.CreateOrder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/orders/track/{statusToken}", wrapper.TrackOrder)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/orders/{orderId}/checkout", wrapper.CreateOrderCheckout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/price", wrapper.Price)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/price/compare", wrapper.PriceCompare)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/quotes", wrapper.SubmitQuote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/quotes/{id}", wrapper.GetQuote)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/ship-dates", wrapper.GetShipDates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/step-quotes", wrapper.SubmitStepQuote)
	})

	return r
}
