package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/JamesHawking/print-cut-ship/backend/internal/pricing"
)

// Reference-part price tables for the material landing pages
// (seo_prompts/02). The frontend must never re-implement the engine, and the
// prerendered pages can't call the API at build time — so this DB-free
// subcommand computes the tables through internal/pricing and the result is
// committed as instant-quote/src/content/reference-prices.json
// (`make gen-reference-prices`; drift pinned by referenceprices_test.go).

type referencePart struct {
	ID             string       `json:"id"`
	VolumeCm3      float64      `json:"volumeCm3"`
	SurfaceAreaCm2 float64      `json:"surfaceAreaCm2"`
	BboxMm         pricing.Vec3 `json:"bboxMm"`
}

// Three canonical example parts: a small solid bracket, a thin-walled
// enclosure, a larger housing. Values are plausible geometry, chosen once —
// changing them changes published marketing tables, so treat as content.
var referenceParts = []referencePart{
	{ID: "bracket", VolumeCm3: 20, SurfaceAreaCm2: 120, BboxMm: pricing.Vec3{X: 80, Y: 60, Z: 30}},
	{ID: "enclosure", VolumeCm3: 60, SurfaceAreaCm2: 480, BboxMm: pricing.Vec3{X: 160, Y: 110, Z: 45}},
	{ID: "housing", VolumeCm3: 100, SurfaceAreaCm2: 700, BboxMm: pricing.Vec3{X: 200, Y: 140, Z: 60}},
}

// The materials with published landing pages (slugs live in
// instant-quote/src/content/materials/slugs.ts).
var referenceMaterials = []string{"petg", "asa", "pa12_cf"}

var referenceQuantities = []int{1, 10, 50}

const referenceLeadTime = "standard"

type referencePricesDoc struct {
	Comment     string                                   `json:"$comment"`
	Currency    string                                   `json:"currency"`
	VatIncluded bool                                     `json:"vatIncluded"`
	LeadTime    string                                   `json:"leadTime"`
	Parts       []referencePart                          `json:"parts"`
	Prices      map[string]map[string]map[string]float64 `json:"prices"`
}

// buildReferencePrices computes unit prices for every published material ×
// reference part × quantity. Output is deterministic: maps marshal with
// sorted keys and there is no timestamp, so regeneration is diff-stable.
func buildReferencePrices() (referencePricesDoc, error) {
	prices := make(map[string]map[string]map[string]float64, len(referenceMaterials))
	for _, material := range referenceMaterials {
		if _, ok := pricing.Default.Process(material); !ok {
			return referencePricesDoc{}, fmt.Errorf("unknown material %q", material)
		}
		perPart := make(map[string]map[string]float64, len(referenceParts))
		for _, part := range referenceParts {
			perQty := make(map[string]float64, len(referenceQuantities))
			for _, qty := range referenceQuantities {
				q := pricing.Default.ComputePartQuote(pricing.MeshMetrics{
					VolumeCm3:      part.VolumeCm3,
					SurfaceAreaCm2: part.SurfaceAreaCm2,
					BboxMm:         part.BboxMm,
				}, pricing.PartConfig{
					Process:  material,
					Quantity: float64(qty),
					LeadTime: referenceLeadTime,
				})
				if q.Blocked {
					return referencePricesDoc{}, fmt.Errorf(
						"reference part %q is blocked for %q — fix the part geometry", part.ID, material)
				}
				perQty[fmt.Sprintf("%d", qty)] = q.UnitPricePln
			}
			perPart[part.ID] = perQty
		}
		prices[material] = perPart
	}
	return referencePricesDoc{
		Comment:     "GENERATED by `make gen-reference-prices` (backend/cmd/api reference-prices) — do not edit; gross PLN unit prices from internal/pricing.",
		Currency:    "PLN",
		VatIncluded: true,
		LeadTime:    referenceLeadTime,
		Parts:       referenceParts,
		Prices:      prices,
	}, nil
}

func referencePrices() error {
	doc, err := buildReferencePrices()
	if err != nil {
		return err
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(doc)
}
