/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/price': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Price a set of parts and compute order totals */
    post: operations['price']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/config': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Pricing catalog for display (processes, lead times, fees) */
    get: operations['getConfig']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ship-dates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Estimated ship dates per lead time (Europe/Warsaw clock) */
    get: operations['getShipDates']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/quotes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit an order request; prices are recomputed server-side */
    post: operations['submitQuote']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orders': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List order requests (submitted quotes) for an email. Prototype access control: the login page gates this with a simulated one-time code, so treat the data as non-sensitive until plan 05 adds real auth. */
    get: operations['listOrders']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/step-quotes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Request a manual quote for a STEP file */
    post: operations['submitStepQuote']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/makerworld/fetch': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Download a MakerWorld model's 3MF via Bambu Cloud */
    post: operations['fetchMakerworldModel']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/files': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Reserve a file record and get a presigned upload URL (dedups by hash) */
    post: operations['createFileUpload']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/files/{fileId}/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Confirm a presigned upload completed; verifies the stored object size */
    post: operations['confirmFileUpload']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @enum {string} */
    ProcessId:
      'pla' | 'petg' | 'pctg' | 'asa' | 'petg_fr' | 'pa12_cf' | 'iglidur'
    /** @enum {string} */
    LeadTimeId: 'economy' | 'standard' | 'express'
    /**
     * @description Supported EU shipping destinations
     * @enum {string}
     */
    EuCountry:
      | 'PL'
      | 'DE'
      | 'FR'
      | 'NL'
      | 'BE'
      | 'CZ'
      | 'AT'
      | 'IT'
      | 'ES'
      | 'SE'
      | 'DK'
      | 'FI'
      | 'IE'
      | 'PT'
      | 'SK'
      | 'SI'
      | 'HU'
      | 'RO'
      | 'LT'
      | 'LV'
      | 'EE'
      | 'LU'
      | 'BG'
      | 'HR'
      | 'GR'
    Vec3Mm: {
      /** Format: double */
      x: number
      /** Format: double */
      y: number
      /** Format: double */
      z: number
    }
    PieceMetrics: {
      bboxMm: components['schemas']['Vec3Mm']
    }
    /** @description Pricing-relevant subset of client-side mesh analysis */
    MeshMetrics: {
      /** Format: double */
      volumeCm3: number
      /** Format: double */
      surfaceAreaCm2: number
      bboxMm: components['schemas']['Vec3Mm']
      usedHullFallback: boolean
      /** @description Per-piece bounding boxes for multi-item 3MF files */
      pieces?: components['schemas']['PieceMetrics'][]
    }
    PricePart: {
      metrics: components['schemas']['MeshMetrics']
      process: components['schemas']['ProcessId']
      quantity: number
      leadTime: components['schemas']['LeadTimeId']
    }
    PriceRequest: {
      parts: components['schemas']['PricePart'][]
    }
    DfmFlag: {
      /** @enum {string} */
      code:
        | 'exceeds_build_volume'
        | 'small_feature'
        | 'min_volume_billed'
        | 'geometry_approximated'
        | 'multi_plate'
      /** @enum {string} */
      severity: 'block' | 'warn' | 'info'
      /** @description English debug prose; the frontend renders from code+params. */
      message?: string
      /** @description Structured values for localized rendering, e.g. {"x": 340}. */
      params?: {
        [key: string]: unknown
      }
      suggestedProcesses?: components['schemas']['ProcessId'][]
    }
    BreakdownLine: {
      /** @enum {string} */
      key: 'material' | 'machine' | 'finishing' | 'plates'
      /** @description English debug prose; the frontend renders from key (+count). */
      label?: string
      /** @description Extra-plate count; only set for key=plates. */
      count?: number
      /** Format: double */
      amountPln: number
    }
    PriceBreak: {
      quantity: number
      /** Format: double */
      unitPricePln: number
      /** Format: double */
      discountFraction: number
    }
    PartQuote: {
      blocked: boolean
      /** Format: double */
      billableVolumeCm3: number
      /**
       * Format: double
       * @description Estimated print weight (shell + infill model)
       */
      weightG: number
      /**
       * Format: double
       * @description Estimated print time in hours
       */
      printHours: number
      /** Format: double */
      unitBasePln: number
      /** Format: double */
      discountFraction: number
      /** Format: double */
      leadTimeMultiplier: number
      /** Format: double */
      unitPricePln: number
      /** Format: double */
      lineTotalPln: number
      breakdown: components['schemas']['BreakdownLine'][]
      dfmFlags: components['schemas']['DfmFlag'][]
      priceBreaks: components['schemas']['PriceBreak'][]
      /** @description Present only for multi-piece 3MF parts */
      pieceCount?: number
      /** @description Present only for multi-piece 3MF parts */
      plates?: number
    }
    OrderTotals: {
      /** Format: double */
      partsSubtotalPln: number
      /** Format: double */
      minOrderTopUpPln: number
      /** Format: double */
      orderFeePln: number
      /** Format: double */
      shippingPln: number
      /** Format: double */
      netTotalPln: number
      /** Format: double */
      vatPln: number
      /** Format: double */
      grossTotalPln: number
      freeShipping: boolean
      minOrderApplied: boolean
    }
    PriceResponse: {
      parts: components['schemas']['PartQuote'][]
      totals: components['schemas']['OrderTotals']
    }
    CatalogProcess: {
      id: components['schemas']['ProcessId']
      label: string
      /** Format: double */
      densityGCm3: number
      /** Format: double */
      plnPerKg: number
      /** Format: double */
      factor: number
      /** Format: double */
      plnPerHour: number
      build: components['schemas']['Vec3Mm']
    }
    CatalogLeadTime: {
      id: components['schemas']['LeadTimeId']
      /** Format: double */
      mult: number
      businessDays: number
    }
    DiscountTier: {
      quantity: number
      /** Format: double */
      fraction: number
    }
    FdmModel: {
      /** Format: double */
      infillFraction: number
      /** Format: double */
      shellThicknessMm: number
      /** Format: double */
      shellGramsPerPrintHour: number
      /** Format: double */
      infillGramsPerPrintHour: number
    }
    CatalogResponse: {
      processes: components['schemas']['CatalogProcess'][]
      leadTimes: components['schemas']['CatalogLeadTime'][]
      discountTiers: components['schemas']['DiscountTier'][]
      fdm: components['schemas']['FdmModel']
      quantityChips: number[]
      maxParts: number
      /** Format: double */
      minOrderPln: number
      /** Format: double */
      minPartPricePln: number
      /** Format: double */
      orderFeePln: number
      /** Format: double */
      shippingFlatPln: number
      /** Format: double */
      freeShippingThresholdPln: number
      /** Format: double */
      vatRate: number
      /** Format: double */
      extraPlateFeePln: number
    }
    CalDate: {
      y: number
      /** @description 1-12 */
      m: number
      d: number
    }
    ShipDate: {
      leadTime: components['schemas']['LeadTimeId']
      date: components['schemas']['CalDate']
      dispatchStartsToday: boolean
      /** @description e.g. "Thu 16 Jul" (canonical engine label; UI formats the date per locale) */
      label: string
    }
    ShipDatesResponse: {
      shipDates: components['schemas']['ShipDate'][]
    }
    SubmitQuotePart: {
      fileName: string
      hash: string
      /**
       * Format: uuid
       * @description The stored file backing this part (plan 02). When present the server verifies it exists with a matching hash and links it.
       */
      fileId?: string
      metrics: components['schemas']['MeshMetrics']
      process: components['schemas']['ProcessId']
      quantity: number
      leadTime: components['schemas']['LeadTimeId']
    }
    SubmitQuoteRequest: {
      /** Format: email */
      email: string
      country: components['schemas']['EuCountry']
      parts: components['schemas']['SubmitQuotePart'][]
      /**
       * Format: double
       * @description The gross total the client displayed, for mismatch telemetry. The server's own computation is authoritative.
       */
      clientGrossTotalPln?: number
      /**
       * @description UI locale at submit time; persisted for downstream emails and invoices (plans 05/06 read it).
       * @default pl
       * @enum {string}
       */
      locale: 'pl' | 'en'
    }
    SubmitQuoteResponse: {
      /** @description e.g. "Q-1A2B3C4D" */
      quoteId: string
      totals: components['schemas']['OrderTotals']
    }
    OrderSummary: {
      /** @description e.g. "Q-1A2B3C4D" */
      quoteId: string
      /** Format: date-time */
      createdAt: string
      /** @enum {string} */
      status: 'submitted' | 'expired' | 'ordered'
      /** Format: double */
      grossTotalPln: number
      partCount: number
      /** @description First part's file name */
      fileName: string
      leadTime: components['schemas']['LeadTimeId']
    }
    ListOrdersResponse: {
      orders: components['schemas']['OrderSummary'][]
    }
    StepQuoteRequest: {
      /** Format: email */
      email: string
      fileName: string
      fileSize: number
    }
    StepQuoteResponse: {
      /** @description e.g. "STEP-1A2B3C4D" */
      requestId: string
    }
    MakerworldFetchRequest: {
      /** Format: int64 */
      designId: number
      /** Format: int64 */
      profileId?: number
    }
    MakerworldError: {
      /** @enum {string} */
      code:
        | 'token_missing'
        | 'design_not_found'
        | 'no_instance'
        | 'auth_expired'
        | 'download_failed'
        | 'too_large'
    }
    CreateFileRequest: {
      sha256: string
      fileName: string
      /** @enum {string} */
      kind: 'stl' | 'obj' | '3mf' | 'step'
      /** Format: int64 */
      sizeBytes: number
    }
    CreateFileResponse: {
      /** Format: uuid */
      fileId: string
      /** @description Presigned PUT URL; absent when alreadyStored is true */
      uploadUrl?: string
      alreadyStored: boolean
    }
    ConfirmFileResponse: {
      /** Format: uuid */
      fileId: string
      stored: boolean
    }
    ApiError: {
      code: components['schemas']['ApiErrorCode']
      /** @description English debug prose; never displayed to users. */
      error: string
      /** @description Structured values for localized rendering, e.g. {"max": 5}. */
      params?: {
        [key: string]: unknown
      }
    }
    /**
     * @description Machine code the frontend dictionary maps to localized copy.
     * @enum {string}
     */
    ApiErrorCode:
      | 'invalid_body'
      | 'parts_count'
      | 'unknown_process'
      | 'unknown_lead_time'
      | 'quantity_range'
      | 'invalid_metrics'
      | 'invalid_email'
      | 'unsupported_country'
      | 'missing_file_fields'
      | 'quote_file_invalid'
      | 'missing_file_name'
      | 'invalid_file_size'
      | 'invalid_design_id'
      | 'invalid_profile_id'
      | 'invalid_hash'
      | 'unsupported_kind'
      | 'file_size_range'
      | 'file_not_found'
      | 'file_missing_hash'
      | 'upload_object_missing'
      | 'upload_size_mismatch'
      | 'storage_unavailable'
      | 'internal'
  }
  responses: {
    /** @description Invalid request payload */
    BadRequest: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ApiError']
      }
    }
    /** @description MakerWorld download failure */
    MakerworldError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['MakerworldError']
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  price: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PriceRequest']
      }
    }
    responses: {
      /** @description Per-part quotes plus order totals */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PriceResponse']
        }
      }
      400: components['responses']['BadRequest']
    }
  }
  getConfig: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The current pricing catalog */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CatalogResponse']
        }
      }
    }
  }
  getShipDates: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Ship date for each lead time */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ShipDatesResponse']
        }
      }
    }
  }
  submitQuote: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmitQuoteRequest']
      }
    }
    responses: {
      /** @description Quote accepted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SubmitQuoteResponse']
        }
      }
      400: components['responses']['BadRequest']
    }
  }
  listOrders: {
    parameters: {
      query: {
        email: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Order requests for the email, newest first */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ListOrdersResponse']
        }
      }
      400: components['responses']['BadRequest']
    }
  }
  submitStepQuote: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['StepQuoteRequest']
      }
    }
    responses: {
      /** @description Manual quote request accepted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StepQuoteResponse']
        }
      }
      400: components['responses']['BadRequest']
    }
  }
  fetchMakerworldModel: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MakerworldFetchRequest']
      }
    }
    responses: {
      /** @description Raw 3MF bytes */
      200: {
        headers: {
          /** @description URI-encoded file name of the downloaded model */
          'X-Mw-Filename'?: string
          [name: string]: unknown
        }
        content: {
          'application/octet-stream': string
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['MakerworldError']
      404: components['responses']['MakerworldError']
      413: components['responses']['MakerworldError']
      502: components['responses']['MakerworldError']
      503: components['responses']['MakerworldError']
    }
  }
  createFileUpload: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateFileRequest']
      }
    }
    responses: {
      /** @description File reserved (uploadUrl present) or already stored */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CreateFileResponse']
        }
      }
      400: components['responses']['BadRequest']
    }
  }
  confirmFileUpload: {
    parameters: {
      query?: never
      header?: never
      path: {
        fileId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Upload confirmed */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConfirmFileResponse']
        }
      }
      400: components['responses']['BadRequest']
      404: components['responses']['BadRequest']
    }
  }
}
