/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/price': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Price a set of parts and compute order totals */
    post: operations['price']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/config': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Pricing catalog for display (processes, lead times, fees) */
    get: operations['getConfig']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ship-dates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Estimated ship dates per lead time (Europe/Warsaw clock) */
    get: operations['getShipDates']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/quotes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit an order request; prices are recomputed server-side */
    post: operations['submitQuote']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/quotes/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read back a submitted quote by its id. The id is an unguessable capability token (the quoteId returned by submitQuote); the response is pricing-only and carries no customer PII. */
    get: operations['getQuote']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/request-code': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Email a 6-digit one-time login code. Always returns 204 — whether the email has orders or not, and whether the resend throttle skipped sending — so the endpoint never reveals which emails exist. 400 only for a malformed email. */
    post: operations['requestLoginCode']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/verify-code': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Verify a 6-digit login code. On success sets the iq_session cookie (httpOnly, SameSite=Lax) and returns 204. Codes are single-use, expire after 10 minutes, and allow at most 5 attempts. */
    post: operations['verifyLoginCode']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Current session's identity (session restore for the frontend) */
    get: operations['getMe']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Delete the current session and clear the cookie */
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orders': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List the signed-in user's orders, newest first. Identity is derived from the session server-side; guest checkouts appear via their email. */
    get: operations['listOrders']
    put?: never
    /** Create a draft order from a persisted quote. The client sends no prices — every money value is copied verbatim from the stored, server-recomputed quote rows (anti-tamper boundary). */
    post: operations['createOrder']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orders/{orderId}/checkout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create (or return the live) payment-provider checkout session for a draft order. The returned URL is provider-hosted (Stripe Checkout in plan 18, a stub page while PAYMENTS_PROVIDER=stub) — the browser redirects to it and never asserts payment itself. */
    post: operations['createOrderCheckout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/orders/track/{statusToken}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Public order status view. The statusToken (returned by createOrder and embedded in the post-payment redirect) is the bearer capability; the response is redacted — no internal ids, no raw provider objects, no PII beyond the line items. */
    get: operations['trackOrder']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/admin/orders/{orderId}/refund': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Refund a paid order (admin only). The provider refund is requested here but the status flip to 'refunded' happens in the payment-event pipeline (request/confirm split — same rule as payment). */
    post: operations['refundOrder']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/step-quotes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Request a manual quote for a STEP file */
    post: operations['submitStepQuote']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/makerworld/fetch': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Download a MakerWorld model's 3MF via Bambu Cloud */
    post: operations['fetchMakerworldModel']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/files': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Reserve a file record and get a presigned upload URL (dedups by hash) */
    post: operations['createFileUpload']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/files/{fileId}/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Confirm a presigned upload completed; verifies the stored object size */
    post: operations['confirmFileUpload']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @enum {string} */
    ProcessId:
      'pla' | 'petg' | 'pctg' | 'asa' | 'petg_fr' | 'pa12_cf' | 'iglidur'
    /** @enum {string} */
    LeadTimeId: 'economy' | 'standard' | 'express'
    /**
     * @description Supported EU shipping destinations
     * @enum {string}
     */
    EuCountry:
      | 'PL'
      | 'DE'
      | 'FR'
      | 'NL'
      | 'BE'
      | 'CZ'
      | 'AT'
      | 'IT'
      | 'ES'
      | 'SE'
      | 'DK'
      | 'FI'
      | 'IE'
      | 'PT'
      | 'SK'
      | 'SI'
      | 'HU'
      | 'RO'
      | 'LT'
      | 'LV'
      | 'EE'
      | 'LU'
      | 'BG'
      | 'HR'
      | 'GR'
    Vec3Mm: {
      /** Format: double */
      x: number
      /** Format: double */
      y: number
      /** Format: double */
      z: number
    }
    PieceMetrics: {
      bboxMm: components['schemas']['Vec3Mm']
    }
    /** @description Pricing-relevant subset of client-side mesh analysis */
    MeshMetrics: {
      /** Format: double */
      volumeCm3: number
      /** Format: double */
      surfaceAreaCm2: number
      bboxMm: components['schemas']['Vec3Mm']
      usedHullFallback: boolean
      /** @description Per-piece bounding boxes for multi-item 3MF files */
      pieces?: components['schemas']['PieceMetrics'][]
    }
    PricePart: {
      metrics: components['schemas']['MeshMetrics']
      process: components['schemas']['ProcessId']
      quantity: number
      leadTime: components['schemas']['LeadTimeId']
    }
    PriceRequest: {
      parts: components['schemas']['PricePart'][]
    }
    DfmFlag: {
      /** @enum {string} */
      code:
        | 'exceeds_build_volume'
        | 'small_feature'
        | 'min_volume_billed'
        | 'geometry_approximated'
        | 'multi_plate'
      /** @enum {string} */
      severity: 'block' | 'warn' | 'info'
      /** @description English debug prose; the frontend renders from code+params. */
      message?: string
      /** @description Structured values for localized rendering, e.g. {"x": 340}. */
      params?: {
        [key: string]: unknown
      }
      suggestedProcesses?: components['schemas']['ProcessId'][]
    }
    BreakdownLine: {
      /** @enum {string} */
      key: 'material' | 'machine' | 'finishing' | 'plates'
      /** @description English debug prose; the frontend renders from key (+count). */
      label?: string
      /** @description Extra-plate count; only set for key=plates. */
      count?: number
      /** Format: double */
      amountPln: number
    }
    PriceBreak: {
      quantity: number
      /** Format: double */
      unitPricePln: number
      /** Format: double */
      discountFraction: number
    }
    PartQuote: {
      blocked: boolean
      /** Format: double */
      billableVolumeCm3: number
      /**
       * Format: double
       * @description Estimated print weight (shell + infill model)
       */
      weightG: number
      /**
       * Format: double
       * @description Estimated print time in hours
       */
      printHours: number
      /** Format: double */
      unitBasePln: number
      /** Format: double */
      discountFraction: number
      /** Format: double */
      leadTimeMultiplier: number
      /** Format: double */
      unitPricePln: number
      /** Format: double */
      lineTotalPln: number
      breakdown: components['schemas']['BreakdownLine'][]
      dfmFlags: components['schemas']['DfmFlag'][]
      priceBreaks: components['schemas']['PriceBreak'][]
      /** @description Present only for multi-piece 3MF parts */
      pieceCount?: number
      /** @description Present only for multi-piece 3MF parts */
      plates?: number
    }
    OrderTotals: {
      /** Format: double */
      partsSubtotalPln: number
      /** Format: double */
      minOrderTopUpPln: number
      /** Format: double */
      orderFeePln: number
      /** Format: double */
      shippingPln: number
      /** Format: double */
      netTotalPln: number
      /** Format: double */
      vatPln: number
      /** Format: double */
      grossTotalPln: number
      freeShipping: boolean
      minOrderApplied: boolean
    }
    PriceResponse: {
      parts: components['schemas']['PartQuote'][]
      totals: components['schemas']['OrderTotals']
    }
    CatalogProcess: {
      id: components['schemas']['ProcessId']
      label: string
      /** Format: double */
      densityGCm3: number
      /** Format: double */
      plnPerKg: number
      /** Format: double */
      factor: number
      /** Format: double */
      plnPerHour: number
      build: components['schemas']['Vec3Mm']
    }
    CatalogLeadTime: {
      id: components['schemas']['LeadTimeId']
      /** Format: double */
      mult: number
      businessDays: number
    }
    DiscountTier: {
      quantity: number
      /** Format: double */
      fraction: number
    }
    FdmModel: {
      /** Format: double */
      infillFraction: number
      /** Format: double */
      shellThicknessMm: number
      /** Format: double */
      shellGramsPerPrintHour: number
      /** Format: double */
      infillGramsPerPrintHour: number
    }
    CatalogResponse: {
      processes: components['schemas']['CatalogProcess'][]
      leadTimes: components['schemas']['CatalogLeadTime'][]
      discountTiers: components['schemas']['DiscountTier'][]
      fdm: components['schemas']['FdmModel']
      quantityChips: number[]
      maxParts: number
      /** Format: double */
      minOrderPln: number
      /** Format: double */
      minPartPricePln: number
      /** Format: double */
      orderFeePln: number
      /** Format: double */
      shippingFlatPln: number
      /** Format: double */
      freeShippingThresholdPln: number
      /** Format: double */
      vatRate: number
      /** Format: double */
      extraPlateFeePln: number
    }
    CalDate: {
      y: number
      /** @description 1-12 */
      m: number
      d: number
    }
    ShipDate: {
      leadTime: components['schemas']['LeadTimeId']
      date: components['schemas']['CalDate']
      dispatchStartsToday: boolean
      /** @description e.g. "Thu 16 Jul" (canonical engine label; UI formats the date per locale) */
      label: string
    }
    ShipDatesResponse: {
      shipDates: components['schemas']['ShipDate'][]
    }
    SubmitQuotePart: {
      fileName: string
      hash: string
      /**
       * Format: uuid
       * @description The stored file backing this part (plan 02). When present the server verifies it exists with a matching hash and links it.
       */
      fileId?: string
      metrics: components['schemas']['MeshMetrics']
      process: components['schemas']['ProcessId']
      quantity: number
      leadTime: components['schemas']['LeadTimeId']
    }
    SubmitQuoteRequest: {
      /** Format: email */
      email: string
      country: components['schemas']['EuCountry']
      parts: components['schemas']['SubmitQuotePart'][]
      /**
       * Format: double
       * @description The gross total the client displayed, for mismatch telemetry. The server's own computation is authoritative.
       */
      clientGrossTotalPln?: number
      /**
       * @description UI locale at submit time; persisted for downstream emails and invoices (plans 05/06 read it).
       * @default pl
       * @enum {string}
       */
      locale: 'pl' | 'en'
    }
    SubmitQuoteResponse: {
      /** @description e.g. "Q-1A2B3C4D" */
      quoteId: string
      totals: components['schemas']['OrderTotals']
    }
    /**
     * @description Order lifecycle state; transitions are owned by the backend state machine (internal/orders).
     * @enum {string}
     */
    OrderStatus:
      | 'draft'
      | 'paid'
      | 'in_production'
      | 'shipped'
      | 'delivered'
      | 'cancelled'
      | 'refunded'
    OrderSummary: {
      /** @description e.g. "O-1A2B3C4D" */
      orderId: string
      /** Format: date-time */
      createdAt: string
      status: components['schemas']['OrderStatus']
      /** Format: double */
      grossTotalPln: number
      partCount: number
      /** @description First item's file name */
      fileName: string
      leadTime: components['schemas']['LeadTimeId']
    }
    Address: {
      /** @description Full name (B2C) or company name (B2B) */
      name: string
      /** @description Street and number */
      street: string
      city: string
      postalCode: string
    }
    CreateOrderRequest: {
      /** @description The quoteId returned by submitQuote, e.g. "Q-1A2B3C4D" */
      quoteId: string
      /** Format: email */
      email: string
      country: components['schemas']['EuCountry']
      /** @description B2B only; presence together with nip implies always-invoice */
      companyName?: string
      /** @description Polish NIP (10 digits); checksum validated server-side */
      nip?: string
      /** @description B2C opt-in for a faktura VAT (B2B is always invoiced) */
      invoiceRequested?: boolean
      shippingAddress: components['schemas']['Address']
      /** @description Absent ⇒ bill to the shipping address */
      billingAddress?: components['schemas']['Address']
    }
    CreateOrderResponse: {
      /** @description e.g. "O-1A2B3C4D" */
      orderId: string
      /** @description Bearer capability for the public status page (GET /api/v1/orders/track/{statusToken}); also embedded in the checkout success redirect. */
      statusToken: string
    }
    CheckoutResponse: {
      /** @description Provider-hosted checkout URL to redirect the browser to */
      url: string
    }
    TrackedOrderItem: {
      fileName: string
      process: components['schemas']['ProcessId']
      quantity: number
      leadTime: components['schemas']['LeadTimeId']
      /** Format: double */
      unitPricePln: number
      /** Format: double */
      lineTotalPln: number
    }
    TrackedOrder: {
      orderId: string
      status: components['schemas']['OrderStatus']
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      paidAt?: string
      items: components['schemas']['TrackedOrderItem'][]
      totals: components['schemas']['OrderTotals']
    }
    ListOrdersResponse: {
      orders: components['schemas']['OrderSummary'][]
    }
    StepQuoteRequest: {
      /** Format: email */
      email: string
      fileName: string
      fileSize: number
    }
    StepQuoteResponse: {
      /** @description e.g. "STEP-1A2B3C4D" */
      requestId: string
    }
    MakerworldFetchRequest: {
      /** Format: int64 */
      designId: number
      /** Format: int64 */
      profileId?: number
    }
    MakerworldError: {
      /** @enum {string} */
      code:
        | 'token_missing'
        | 'design_not_found'
        | 'no_instance'
        | 'auth_expired'
        | 'download_failed'
        | 'too_large'
    }
    CreateFileRequest: {
      sha256: string
      fileName: string
      /** @enum {string} */
      kind: 'stl' | 'obj' | '3mf' | 'step'
      /** Format: int64 */
      sizeBytes: number
    }
    CreateFileResponse: {
      /** Format: uuid */
      fileId: string
      /** @description Presigned PUT URL; absent when alreadyStored is true */
      uploadUrl?: string
      alreadyStored: boolean
    }
    ConfirmFileResponse: {
      /** Format: uuid */
      fileId: string
      stored: boolean
    }
    RequestCodeRequest: {
      /** Format: email */
      email: string
    }
    VerifyCodeRequest: {
      /** Format: email */
      email: string
      code: string
    }
    MeResponse: {
      /** Format: email */
      email: string
    }
    ApiError: {
      code: components['schemas']['ApiErrorCode']
      /** @description English debug prose; never displayed to users. */
      error: string
      /** @description Structured values for localized rendering, e.g. {"max": 5}. */
      params?: {
        [key: string]: unknown
      }
    }
    /**
     * @description Machine code the frontend dictionary maps to localized copy.
     * @enum {string}
     */
    ApiErrorCode:
      | 'invalid_body'
      | 'parts_count'
      | 'unknown_process'
      | 'unknown_lead_time'
      | 'quantity_range'
      | 'invalid_metrics'
      | 'invalid_email'
      | 'unsupported_country'
      | 'missing_file_fields'
      | 'quote_file_invalid'
      | 'quote_not_found'
      | 'missing_file_name'
      | 'invalid_file_size'
      | 'invalid_design_id'
      | 'invalid_profile_id'
      | 'invalid_hash'
      | 'unsupported_kind'
      | 'file_size_range'
      | 'file_not_found'
      | 'file_missing_hash'
      | 'upload_object_missing'
      | 'upload_size_mismatch'
      | 'storage_unavailable'
      | 'code_invalid'
      | 'code_expired'
      | 'too_many_attempts'
      | 'unauthorized'
      | 'order_not_found'
      | 'order_wrong_state'
      | 'quote_already_ordered'
      | 'invalid_nip'
      | 'internal'
  }
  responses: {
    /** @description Invalid request payload */
    BadRequest: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ApiError']
      }
    }
    /** @description Resource not found */
    NotFound: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ApiError']
      }
    }
    /** @description Missing, invalid, or expired credentials/session */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ApiError']
      }
    }
    /** @description Authenticated but lacking the required role */
    Forbidden: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ApiError']
      }
    }
    /** @description The resource is in the wrong state for this operation */
    Conflict: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ApiError']
      }
    }
    /** @description MakerWorld download failure */
    MakerworldError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['MakerworldError']
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  price: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PriceRequest']
      }
    }
    responses: {
      /** @description Per-part quotes plus order totals */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PriceResponse']
        }
      }
      400: components['responses']['BadRequest']
    }
  }
  getConfig: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The current pricing catalog */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CatalogResponse']
        }
      }
    }
  }
  getShipDates: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Ship date for each lead time */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ShipDatesResponse']
        }
      }
    }
  }
  submitQuote: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmitQuoteRequest']
      }
    }
    responses: {
      /** @description Quote accepted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SubmitQuoteResponse']
        }
      }
      400: components['responses']['BadRequest']
    }
  }
  getQuote: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The quoteId returned by submitQuote, e.g. "Q-1A2B3C4D" */
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Quote found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SubmitQuoteResponse']
        }
      }
      404: components['responses']['NotFound']
    }
  }
  requestLoginCode: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RequestCodeRequest']
      }
    }
    responses: {
      /** @description Code sent (or silently throttled) */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequest']
    }
  }
  verifyLoginCode: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyCodeRequest']
      }
    }
    responses: {
      /** @description Code accepted; session cookie set */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      400: components['responses']['BadRequest']
      401: components['responses']['UnauthorizedError']
    }
  }
  getMe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The signed-in user */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Session deleted; cookie cleared */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  listOrders: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Orders for the session's user or email, newest first */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ListOrdersResponse']
        }
      }
      401: components['responses']['UnauthorizedError']
    }
  }
  createOrder: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateOrderRequest']
      }
    }
    responses: {
      /** @description Draft order created */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CreateOrderResponse']
        }
      }
      400: components['responses']['BadRequest']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  createOrderCheckout: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The orderId returned by createOrder, e.g. "O-1A2B3C4D" */
        orderId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Checkout session URL to redirect the browser to */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CheckoutResponse']
        }
      }
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  trackOrder: {
    parameters: {
      query?: never
      header?: never
      path: {
        statusToken: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Redacted order view */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TrackedOrder']
        }
      }
      404: components['responses']['NotFound']
    }
  }
  refundOrder: {
    parameters: {
      query?: never
      header?: never
      path: {
        orderId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Refund requested; status flips when the provider confirms */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['UnauthorizedError']
      403: components['responses']['Forbidden']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
    }
  }
  submitStepQuote: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['StepQuoteRequest']
      }
    }
    responses: {
      /** @description Manual quote request accepted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StepQuoteResponse']
        }
      }
      400: components['responses']['BadRequest']
    }
  }
  fetchMakerworldModel: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MakerworldFetchRequest']
      }
    }
    responses: {
      /** @description Raw 3MF bytes */
      200: {
        headers: {
          /** @description URI-encoded file name of the downloaded model */
          'X-Mw-Filename'?: string
          [name: string]: unknown
        }
        content: {
          'application/octet-stream': string
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['MakerworldError']
      404: components['responses']['MakerworldError']
      413: components['responses']['MakerworldError']
      502: components['responses']['MakerworldError']
      503: components['responses']['MakerworldError']
    }
  }
  createFileUpload: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateFileRequest']
      }
    }
    responses: {
      /** @description File reserved (uploadUrl present) or already stored */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CreateFileResponse']
        }
      }
      400: components['responses']['BadRequest']
    }
  }
  confirmFileUpload: {
    parameters: {
      query?: never
      header?: never
      path: {
        fileId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Upload confirmed */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConfirmFileResponse']
        }
      }
      400: components['responses']['BadRequest']
      404: components['responses']['BadRequest']
    }
  }
}
